// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息ID
type MessageID int32

const (
	MessageID_MSG_Ping               MessageID = 0
	MessageID_MSG_Pong               MessageID = 1
	MessageID_MSG_Login_C2S          MessageID = 2
	MessageID_MSG_Login_S2C          MessageID = 3
	MessageID_MSG_Logout_C2S         MessageID = 4
	MessageID_MSG_Logout_S2C         MessageID = 5
	MessageID_MSG_JoinRoom_C2S       MessageID = 6
	MessageID_MSG_JoinRoom_S2C       MessageID = 7
	MessageID_MSG_EnterRoom_S2C      MessageID = 8
	MessageID_MSG_LeaveRoom_C2S      MessageID = 9
	MessageID_MSG_LeaveRoom_S2C      MessageID = 10
	MessageID_MSG_ActionTime_S2C     MessageID = 11
	MessageID_MSG_PlayerAction_C2S   MessageID = 12
	MessageID_MSG_PlayerAction_S2C   MessageID = 13
	MessageID_MSG_PotChangeMoney_S2C MessageID = 14
	MessageID_MSG_UptPlayerList_S2C  MessageID = 15
	MessageID_MSG_ResultData_S2C     MessageID = 16
	MessageID_MSG_BankerData_C2S     MessageID = 17
	MessageID_MSG_BankerData_S2C     MessageID = 18
	MessageID_MSG_EmojiChat_C2S      MessageID = 19
	MessageID_MSG_EmojiChat_S2C      MessageID = 20
)

var MessageID_name = map[int32]string{
	0:  "MSG_Ping",
	1:  "MSG_Pong",
	2:  "MSG_Login_C2S",
	3:  "MSG_Login_S2C",
	4:  "MSG_Logout_C2S",
	5:  "MSG_Logout_S2C",
	6:  "MSG_JoinRoom_C2S",
	7:  "MSG_JoinRoom_S2C",
	8:  "MSG_EnterRoom_S2C",
	9:  "MSG_LeaveRoom_C2S",
	10: "MSG_LeaveRoom_S2C",
	11: "MSG_ActionTime_S2C",
	12: "MSG_PlayerAction_C2S",
	13: "MSG_PlayerAction_S2C",
	14: "MSG_PotChangeMoney_S2C",
	15: "MSG_UptPlayerList_S2C",
	16: "MSG_ResultData_S2C",
	17: "MSG_BankerData_C2S",
	18: "MSG_BankerData_S2C",
	19: "MSG_EmojiChat_C2S",
	20: "MSG_EmojiChat_S2C",
}

var MessageID_value = map[string]int32{
	"MSG_Ping":               0,
	"MSG_Pong":               1,
	"MSG_Login_C2S":          2,
	"MSG_Login_S2C":          3,
	"MSG_Logout_C2S":         4,
	"MSG_Logout_S2C":         5,
	"MSG_JoinRoom_C2S":       6,
	"MSG_JoinRoom_S2C":       7,
	"MSG_EnterRoom_S2C":      8,
	"MSG_LeaveRoom_C2S":      9,
	"MSG_LeaveRoom_S2C":      10,
	"MSG_ActionTime_S2C":     11,
	"MSG_PlayerAction_C2S":   12,
	"MSG_PlayerAction_S2C":   13,
	"MSG_PotChangeMoney_S2C": 14,
	"MSG_UptPlayerList_S2C":  15,
	"MSG_ResultData_S2C":     16,
	"MSG_BankerData_C2S":     17,
	"MSG_BankerData_S2C":     18,
	"MSG_EmojiChat_C2S":      19,
	"MSG_EmojiChat_S2C":      20,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

// 游戏阶段
type GameStep int32

const (
	GameStep_XX_Step GameStep = 0
	GameStep_Banker  GameStep = 1
	GameStep_DownBet GameStep = 2
	GameStep_Settle  GameStep = 3
)

var GameStep_name = map[int32]string{
	0: "XX_Step",
	1: "Banker",
	2: "DownBet",
	3: "Settle",
}

var GameStep_value = map[string]int32{
	"XX_Step": 0,
	"Banker":  1,
	"DownBet": 2,
	"Settle":  3,
}

func (x GameStep) String() string {
	return proto.EnumName(GameStep_name, int32(x))
}

func (GameStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type PlayerStatus int32

const (
	PlayerStatus_XX_Status PlayerStatus = 0
	PlayerStatus_PlayGame  PlayerStatus = 1
	PlayerStatus_WatchGame PlayerStatus = 2
)

var PlayerStatus_name = map[int32]string{
	0: "XX_Status",
	1: "PlayGame",
	2: "WatchGame",
}

var PlayerStatus_value = map[string]int32{
	"XX_Status": 0,
	"PlayGame":  1,
	"WatchGame": 2,
}

func (x PlayerStatus) String() string {
	return proto.EnumName(PlayerStatus_name, int32(x))
}

func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

type BankerStatus int32

const (
	BankerStatus_BankerNot  BankerStatus = 0
	BankerStatus_BankerNow  BankerStatus = 1
	BankerStatus_BankerUp   BankerStatus = 2
	BankerStatus_BankerDown BankerStatus = 3
)

var BankerStatus_name = map[int32]string{
	0: "BankerNot",
	1: "BankerNow",
	2: "BankerUp",
	3: "BankerDown",
}

var BankerStatus_value = map[string]int32{
	"BankerNot":  0,
	"BankerNow":  1,
	"BankerUp":   2,
	"BankerDown": 3,
}

func (x BankerStatus) String() string {
	return proto.EnumName(BankerStatus_name, int32(x))
}

func (BankerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

//注池类型
type PotType int32

const (
	PotType_XX_Pot      PotType = 0
	PotType_BigPot      PotType = 1
	PotType_SmallPot    PotType = 2
	PotType_SinglePot   PotType = 3
	PotType_DoublePot   PotType = 4
	PotType_PairPot     PotType = 5
	PotType_StraightPot PotType = 6
	PotType_LeopardPot  PotType = 7
)

var PotType_name = map[int32]string{
	0: "XX_Pot",
	1: "BigPot",
	2: "SmallPot",
	3: "SinglePot",
	4: "DoublePot",
	5: "PairPot",
	6: "StraightPot",
	7: "LeopardPot",
}

var PotType_value = map[string]int32{
	"XX_Pot":      0,
	"BigPot":      1,
	"SmallPot":    2,
	"SinglePot":   3,
	"DoublePot":   4,
	"PairPot":     5,
	"StraightPot": 6,
	"LeopardPot":  7,
}

func (x PotType) String() string {
	return proto.EnumName(PotType_name, int32(x))
}

func (PotType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

//卡牌类型
type CardsType int32

const (
	CardsType_XX_Card  CardsType = 0
	CardsType_Pair     CardsType = 1
	CardsType_Straight CardsType = 2
	CardsType_Leopard  CardsType = 3
)

var CardsType_name = map[int32]string{
	0: "XX_Card",
	1: "Pair",
	2: "Straight",
	3: "Leopard",
}

var CardsType_value = map[string]int32{
	"XX_Card":  0,
	"Pair":     1,
	"Straight": 2,
	"Leopard":  3,
}

func (x CardsType) String() string {
	return proto.EnumName(CardsType_name, int32(x))
}

func (CardsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Account              float64  `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Login_C2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C2S) Reset()         { *m = Login_C2S{} }
func (m *Login_C2S) String() string { return proto.CompactTextString(m) }
func (*Login_C2S) ProtoMessage()    {}
func (*Login_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Login_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C2S.Unmarshal(m, b)
}
func (m *Login_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C2S.Marshal(b, m, deterministic)
}
func (m *Login_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C2S.Merge(m, src)
}
func (m *Login_C2S) XXX_Size() int {
	return xxx_messageInfo_Login_C2S.Size(m)
}
func (m *Login_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C2S proto.InternalMessageInfo

func (m *Login_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Login_C2S) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Login_C2S) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Login_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	Backroom             bool        `protobuf:"varint,2,opt,name=backroom,proto3" json:"backroom,omitempty"`
	PlayerNum            int32       `protobuf:"varint,3,opt,name=PlayerNum,proto3" json:"PlayerNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Login_S2C) Reset()         { *m = Login_S2C{} }
func (m *Login_S2C) String() string { return proto.CompactTextString(m) }
func (*Login_S2C) ProtoMessage()    {}
func (*Login_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Login_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S2C.Unmarshal(m, b)
}
func (m *Login_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S2C.Marshal(b, m, deterministic)
}
func (m *Login_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S2C.Merge(m, src)
}
func (m *Login_S2C) XXX_Size() int {
	return xxx_messageInfo_Login_S2C.Size(m)
}
func (m *Login_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S2C proto.InternalMessageInfo

func (m *Login_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Login_S2C) GetBackroom() bool {
	if m != nil {
		return m.Backroom
	}
	return false
}

func (m *Login_S2C) GetPlayerNum() int32 {
	if m != nil {
		return m.PlayerNum
	}
	return 0
}

type Logout_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_C2S) Reset()         { *m = Logout_C2S{} }
func (m *Logout_C2S) String() string { return proto.CompactTextString(m) }
func (*Logout_C2S) ProtoMessage()    {}
func (*Logout_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Logout_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_C2S.Unmarshal(m, b)
}
func (m *Logout_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_C2S.Marshal(b, m, deterministic)
}
func (m *Logout_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_C2S.Merge(m, src)
}
func (m *Logout_C2S) XXX_Size() int {
	return xxx_messageInfo_Logout_C2S.Size(m)
}
func (m *Logout_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_C2S proto.InternalMessageInfo

type Logout_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_S2C) Reset()         { *m = Logout_S2C{} }
func (m *Logout_S2C) String() string { return proto.CompactTextString(m) }
func (*Logout_S2C) ProtoMessage()    {}
func (*Logout_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Logout_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_S2C.Unmarshal(m, b)
}
func (m *Logout_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_S2C.Marshal(b, m, deterministic)
}
func (m *Logout_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_S2C.Merge(m, src)
}
func (m *Logout_S2C) XXX_Size() int {
	return xxx_messageInfo_Logout_S2C.Size(m)
}
func (m *Logout_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_S2C proto.InternalMessageInfo

//玩家各注池下注的金额
type DownBetMoney struct {
	BigDownBet           int32    `protobuf:"varint,1,opt,name=BigDownBet,proto3" json:"BigDownBet,omitempty"`
	SmallDownBet         int32    `protobuf:"varint,2,opt,name=SmallDownBet,proto3" json:"SmallDownBet,omitempty"`
	SingleDownBet        int32    `protobuf:"varint,3,opt,name=SingleDownBet,proto3" json:"SingleDownBet,omitempty"`
	DoubleDownBet        int32    `protobuf:"varint,4,opt,name=DoubleDownBet,proto3" json:"DoubleDownBet,omitempty"`
	PairDownBet          int32    `protobuf:"varint,5,opt,name=PairDownBet,proto3" json:"PairDownBet,omitempty"`
	StraightDownBet      int32    `protobuf:"varint,6,opt,name=StraightDownBet,proto3" json:"StraightDownBet,omitempty"`
	LeopardDownBet       int32    `protobuf:"varint,7,opt,name=LeopardDownBet,proto3" json:"LeopardDownBet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownBetMoney) Reset()         { *m = DownBetMoney{} }
func (m *DownBetMoney) String() string { return proto.CompactTextString(m) }
func (*DownBetMoney) ProtoMessage()    {}
func (*DownBetMoney) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *DownBetMoney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownBetMoney.Unmarshal(m, b)
}
func (m *DownBetMoney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownBetMoney.Marshal(b, m, deterministic)
}
func (m *DownBetMoney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownBetMoney.Merge(m, src)
}
func (m *DownBetMoney) XXX_Size() int {
	return xxx_messageInfo_DownBetMoney.Size(m)
}
func (m *DownBetMoney) XXX_DiscardUnknown() {
	xxx_messageInfo_DownBetMoney.DiscardUnknown(m)
}

var xxx_messageInfo_DownBetMoney proto.InternalMessageInfo

func (m *DownBetMoney) GetBigDownBet() int32 {
	if m != nil {
		return m.BigDownBet
	}
	return 0
}

func (m *DownBetMoney) GetSmallDownBet() int32 {
	if m != nil {
		return m.SmallDownBet
	}
	return 0
}

func (m *DownBetMoney) GetSingleDownBet() int32 {
	if m != nil {
		return m.SingleDownBet
	}
	return 0
}

func (m *DownBetMoney) GetDoubleDownBet() int32 {
	if m != nil {
		return m.DoubleDownBet
	}
	return 0
}

func (m *DownBetMoney) GetPairDownBet() int32 {
	if m != nil {
		return m.PairDownBet
	}
	return 0
}

func (m *DownBetMoney) GetStraightDownBet() int32 {
	if m != nil {
		return m.StraightDownBet
	}
	return 0
}

func (m *DownBetMoney) GetLeopardDownBet() int32 {
	if m != nil {
		return m.LeopardDownBet
	}
	return 0
}

type PotWinList struct {
	ResultNum            int32     `protobuf:"varint,1,opt,name=resultNum,proto3" json:"resultNum,omitempty"`
	BigSmall             int32     `protobuf:"varint,2,opt,name=bigSmall,proto3" json:"bigSmall,omitempty"`
	SinDouble            int32     `protobuf:"varint,3,opt,name=sinDouble,proto3" json:"sinDouble,omitempty"`
	CardType             CardsType `protobuf:"varint,4,opt,name=cardType,proto3,enum=msg.CardsType" json:"cardType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PotWinList) Reset()         { *m = PotWinList{} }
func (m *PotWinList) String() string { return proto.CompactTextString(m) }
func (*PotWinList) ProtoMessage()    {}
func (*PotWinList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *PotWinList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotWinList.Unmarshal(m, b)
}
func (m *PotWinList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotWinList.Marshal(b, m, deterministic)
}
func (m *PotWinList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotWinList.Merge(m, src)
}
func (m *PotWinList) XXX_Size() int {
	return xxx_messageInfo_PotWinList.Size(m)
}
func (m *PotWinList) XXX_DiscardUnknown() {
	xxx_messageInfo_PotWinList.DiscardUnknown(m)
}

var xxx_messageInfo_PotWinList proto.InternalMessageInfo

func (m *PotWinList) GetResultNum() int32 {
	if m != nil {
		return m.ResultNum
	}
	return 0
}

func (m *PotWinList) GetBigSmall() int32 {
	if m != nil {
		return m.BigSmall
	}
	return 0
}

func (m *PotWinList) GetSinDouble() int32 {
	if m != nil {
		return m.SinDouble
	}
	return 0
}

func (m *PotWinList) GetCardType() CardsType {
	if m != nil {
		return m.CardType
	}
	return CardsType_XX_Card
}

type PlayerData struct {
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	DownBetMoney         *DownBetMoney `protobuf:"bytes,2,opt,name=downBetMoney,proto3" json:"downBetMoney,omitempty"`
	Status               PlayerStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=msg.PlayerStatus" json:"status,omitempty"`
	TotalDownBet         int32         `protobuf:"varint,4,opt,name=totalDownBet,proto3" json:"totalDownBet,omitempty"`
	WinTotalCount        int32         `protobuf:"varint,5,opt,name=winTotalCount,proto3" json:"winTotalCount,omitempty"`
	ResultMoney          float64       `protobuf:"fixed64,6,opt,name=resultMoney,proto3" json:"resultMoney,omitempty"`
	PotWinList           []*PotWinList `protobuf:"bytes,7,rep,name=potWinList,proto3" json:"potWinList,omitempty"`
	IsAction             bool          `protobuf:"varint,8,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	IsBanker             bool          `protobuf:"varint,9,opt,name=IsBanker,proto3" json:"IsBanker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetDownBetMoney() *DownBetMoney {
	if m != nil {
		return m.DownBetMoney
	}
	return nil
}

func (m *PlayerData) GetStatus() PlayerStatus {
	if m != nil {
		return m.Status
	}
	return PlayerStatus_XX_Status
}

func (m *PlayerData) GetTotalDownBet() int32 {
	if m != nil {
		return m.TotalDownBet
	}
	return 0
}

func (m *PlayerData) GetWinTotalCount() int32 {
	if m != nil {
		return m.WinTotalCount
	}
	return 0
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil {
		return m.ResultMoney
	}
	return 0
}

func (m *PlayerData) GetPotWinList() []*PotWinList {
	if m != nil {
		return m.PotWinList
	}
	return nil
}

func (m *PlayerData) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerData) GetIsBanker() bool {
	if m != nil {
		return m.IsBanker
	}
	return false
}

type RoomData struct {
	RoomId               string        `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerData           []*PlayerData `protobuf:"bytes,2,rep,name=playerData,proto3" json:"playerData,omitempty"`
	GameTime             int32         `protobuf:"varint,3,opt,name=gameTime,proto3" json:"gameTime,omitempty"`
	GameStep             GameStep      `protobuf:"varint,4,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	ResultInt            []int32       `protobuf:"varint,5,rep,packed,name=resultInt,proto3" json:"resultInt,omitempty"`
	PotMoneyCount        *DownBetMoney `protobuf:"bytes,6,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	PotWinList           []*PotWinList `protobuf:"bytes,7,rep,name=potWinList,proto3" json:"potWinList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetPlayerData() []*PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *RoomData) GetGameTime() int32 {
	if m != nil {
		return m.GameTime
	}
	return 0
}

func (m *RoomData) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_XX_Step
}

func (m *RoomData) GetResultInt() []int32 {
	if m != nil {
		return m.ResultInt
	}
	return nil
}

func (m *RoomData) GetPotMoneyCount() *DownBetMoney {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

func (m *RoomData) GetPotWinList() []*PotWinList {
	if m != nil {
		return m.PotWinList
	}
	return nil
}

type JoinRoom_C2S struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom_C2S) Reset()         { *m = JoinRoom_C2S{} }
func (m *JoinRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_C2S) ProtoMessage()    {}
func (*JoinRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *JoinRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_C2S.Unmarshal(m, b)
}
func (m *JoinRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_C2S.Marshal(b, m, deterministic)
}
func (m *JoinRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_C2S.Merge(m, src)
}
func (m *JoinRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_C2S.Size(m)
}
func (m *JoinRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_C2S proto.InternalMessageInfo

func (m *JoinRoom_C2S) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type JoinRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoom_S2C) Reset()         { *m = JoinRoom_S2C{} }
func (m *JoinRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_S2C) ProtoMessage()    {}
func (*JoinRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *JoinRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_S2C.Unmarshal(m, b)
}
func (m *JoinRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_S2C.Marshal(b, m, deterministic)
}
func (m *JoinRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_S2C.Merge(m, src)
}
func (m *JoinRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_S2C.Size(m)
}
func (m *JoinRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_S2C proto.InternalMessageInfo

func (m *JoinRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type EnterRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoom_S2C) Reset()         { *m = EnterRoom_S2C{} }
func (m *EnterRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoom_S2C) ProtoMessage()    {}
func (*EnterRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *EnterRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoom_S2C.Unmarshal(m, b)
}
func (m *EnterRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoom_S2C.Marshal(b, m, deterministic)
}
func (m *EnterRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoom_S2C.Merge(m, src)
}
func (m *EnterRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoom_S2C.Size(m)
}
func (m *EnterRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoom_S2C proto.InternalMessageInfo

func (m *EnterRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type LeaveRoom_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom_C2S) Reset()         { *m = LeaveRoom_C2S{} }
func (m *LeaveRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_C2S) ProtoMessage()    {}
func (*LeaveRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *LeaveRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_C2S.Unmarshal(m, b)
}
func (m *LeaveRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_C2S.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_C2S.Merge(m, src)
}
func (m *LeaveRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_C2S.Size(m)
}
func (m *LeaveRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_C2S proto.InternalMessageInfo

type LeaveRoom_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LeaveRoom_S2C) Reset()         { *m = LeaveRoom_S2C{} }
func (m *LeaveRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_S2C) ProtoMessage()    {}
func (*LeaveRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *LeaveRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_S2C.Unmarshal(m, b)
}
func (m *LeaveRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_S2C.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_S2C.Merge(m, src)
}
func (m *LeaveRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_S2C.Size(m)
}
func (m *LeaveRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_S2C proto.InternalMessageInfo

func (m *LeaveRoom_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type ActionTime_S2C struct {
	StartTime            int32    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	GameStep             GameStep `protobuf:"varint,2,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionTime_S2C) Reset()         { *m = ActionTime_S2C{} }
func (m *ActionTime_S2C) String() string { return proto.CompactTextString(m) }
func (*ActionTime_S2C) ProtoMessage()    {}
func (*ActionTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{16}
}

func (m *ActionTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionTime_S2C.Unmarshal(m, b)
}
func (m *ActionTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionTime_S2C.Marshal(b, m, deterministic)
}
func (m *ActionTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionTime_S2C.Merge(m, src)
}
func (m *ActionTime_S2C) XXX_Size() int {
	return xxx_messageInfo_ActionTime_S2C.Size(m)
}
func (m *ActionTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ActionTime_S2C proto.InternalMessageInfo

func (m *ActionTime_S2C) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ActionTime_S2C) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_XX_Step
}

type PlayerAction_C2S struct {
	DownBet              int32    `protobuf:"varint,1,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,2,opt,name=downPot,proto3,enum=msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,3,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_C2S) Reset()         { *m = PlayerAction_C2S{} }
func (m *PlayerAction_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_C2S) ProtoMessage()    {}
func (*PlayerAction_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{17}
}

func (m *PlayerAction_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_C2S.Unmarshal(m, b)
}
func (m *PlayerAction_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerAction_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_C2S.Merge(m, src)
}
func (m *PlayerAction_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_C2S.Size(m)
}
func (m *PlayerAction_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_C2S proto.InternalMessageInfo

func (m *PlayerAction_C2S) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_C2S) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XX_Pot
}

func (m *PlayerAction_C2S) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

type PlayerAction_S2C struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DownBet              int32    `protobuf:"varint,2,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,3,opt,name=downPot,proto3,enum=msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,4,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	Account              float64  `protobuf:"fixed64,5,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_S2C) Reset()         { *m = PlayerAction_S2C{} }
func (m *PlayerAction_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_S2C) ProtoMessage()    {}
func (*PlayerAction_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{18}
}

func (m *PlayerAction_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_S2C.Unmarshal(m, b)
}
func (m *PlayerAction_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerAction_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_S2C.Merge(m, src)
}
func (m *PlayerAction_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_S2C.Size(m)
}
func (m *PlayerAction_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_S2C proto.InternalMessageInfo

func (m *PlayerAction_S2C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerAction_S2C) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_S2C) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XX_Pot
}

func (m *PlayerAction_S2C) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerAction_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

// 广播注池金额变化
type PotChangeMoney_S2C struct {
	PotMoneyCount        *DownBetMoney `protobuf:"bytes,1,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PotChangeMoney_S2C) Reset()         { *m = PotChangeMoney_S2C{} }
func (m *PotChangeMoney_S2C) String() string { return proto.CompactTextString(m) }
func (*PotChangeMoney_S2C) ProtoMessage()    {}
func (*PotChangeMoney_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{19}
}

func (m *PotChangeMoney_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotChangeMoney_S2C.Unmarshal(m, b)
}
func (m *PotChangeMoney_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotChangeMoney_S2C.Marshal(b, m, deterministic)
}
func (m *PotChangeMoney_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotChangeMoney_S2C.Merge(m, src)
}
func (m *PotChangeMoney_S2C) XXX_Size() int {
	return xxx_messageInfo_PotChangeMoney_S2C.Size(m)
}
func (m *PotChangeMoney_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PotChangeMoney_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PotChangeMoney_S2C proto.InternalMessageInfo

func (m *PotChangeMoney_S2C) GetPotMoneyCount() *DownBetMoney {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

// 更新房间用户列表
type UptPlayerList_S2C struct {
	PlayerList           []*PlayerData `protobuf:"bytes,1,rep,name=playerList,proto3" json:"playerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UptPlayerList_S2C) Reset()         { *m = UptPlayerList_S2C{} }
func (m *UptPlayerList_S2C) String() string { return proto.CompactTextString(m) }
func (*UptPlayerList_S2C) ProtoMessage()    {}
func (*UptPlayerList_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{20}
}

func (m *UptPlayerList_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UptPlayerList_S2C.Unmarshal(m, b)
}
func (m *UptPlayerList_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UptPlayerList_S2C.Marshal(b, m, deterministic)
}
func (m *UptPlayerList_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UptPlayerList_S2C.Merge(m, src)
}
func (m *UptPlayerList_S2C) XXX_Size() int {
	return xxx_messageInfo_UptPlayerList_S2C.Size(m)
}
func (m *UptPlayerList_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_UptPlayerList_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_UptPlayerList_S2C proto.InternalMessageInfo

func (m *UptPlayerList_S2C) GetPlayerList() []*PlayerData {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

type ResultData_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResultData_S2C) Reset()         { *m = ResultData_S2C{} }
func (m *ResultData_S2C) String() string { return proto.CompactTextString(m) }
func (*ResultData_S2C) ProtoMessage()    {}
func (*ResultData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{21}
}

func (m *ResultData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultData_S2C.Unmarshal(m, b)
}
func (m *ResultData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultData_S2C.Marshal(b, m, deterministic)
}
func (m *ResultData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData_S2C.Merge(m, src)
}
func (m *ResultData_S2C) XXX_Size() int {
	return xxx_messageInfo_ResultData_S2C.Size(m)
}
func (m *ResultData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData_S2C proto.InternalMessageInfo

func (m *ResultData_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type BankerData_C2S struct {
	Status               BankerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=msg.BankerStatus" json:"status,omitempty"`
	TakeMoney            int32        `protobuf:"varint,2,opt,name=takeMoney,proto3" json:"takeMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BankerData_C2S) Reset()         { *m = BankerData_C2S{} }
func (m *BankerData_C2S) String() string { return proto.CompactTextString(m) }
func (*BankerData_C2S) ProtoMessage()    {}
func (*BankerData_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{22}
}

func (m *BankerData_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankerData_C2S.Unmarshal(m, b)
}
func (m *BankerData_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankerData_C2S.Marshal(b, m, deterministic)
}
func (m *BankerData_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankerData_C2S.Merge(m, src)
}
func (m *BankerData_C2S) XXX_Size() int {
	return xxx_messageInfo_BankerData_C2S.Size(m)
}
func (m *BankerData_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_BankerData_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_BankerData_C2S proto.InternalMessageInfo

func (m *BankerData_C2S) GetStatus() BankerStatus {
	if m != nil {
		return m.Status
	}
	return BankerStatus_BankerNot
}

func (m *BankerData_C2S) GetTakeMoney() int32 {
	if m != nil {
		return m.TakeMoney
	}
	return 0
}

type BankerData_S2C struct {
	PlayerList           *PlayerData `protobuf:"bytes,1,opt,name=playerList,proto3" json:"playerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BankerData_S2C) Reset()         { *m = BankerData_S2C{} }
func (m *BankerData_S2C) String() string { return proto.CompactTextString(m) }
func (*BankerData_S2C) ProtoMessage()    {}
func (*BankerData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{23}
}

func (m *BankerData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankerData_S2C.Unmarshal(m, b)
}
func (m *BankerData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankerData_S2C.Marshal(b, m, deterministic)
}
func (m *BankerData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankerData_S2C.Merge(m, src)
}
func (m *BankerData_S2C) XXX_Size() int {
	return xxx_messageInfo_BankerData_S2C.Size(m)
}
func (m *BankerData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_BankerData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_BankerData_S2C proto.InternalMessageInfo

func (m *BankerData_S2C) GetPlayerList() *PlayerData {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

// 表情发送
type EmojiChat_C2S struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	GoalId               string   `protobuf:"bytes,2,opt,name=goalId,proto3" json:"goalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_C2S) Reset()         { *m = EmojiChat_C2S{} }
func (m *EmojiChat_C2S) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_C2S) ProtoMessage()    {}
func (*EmojiChat_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{24}
}

func (m *EmojiChat_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_C2S.Unmarshal(m, b)
}
func (m *EmojiChat_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_C2S.Marshal(b, m, deterministic)
}
func (m *EmojiChat_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_C2S.Merge(m, src)
}
func (m *EmojiChat_C2S) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_C2S.Size(m)
}
func (m *EmojiChat_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_C2S proto.InternalMessageInfo

func (m *EmojiChat_C2S) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_C2S) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

// 表情发送
type EmojiChat_S2C struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	ActId                string   `protobuf:"bytes,2,opt,name=actId,proto3" json:"actId,omitempty"`
	GoalId               string   `protobuf:"bytes,3,opt,name=goalId,proto3" json:"goalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_S2C) Reset()         { *m = EmojiChat_S2C{} }
func (m *EmojiChat_S2C) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_S2C) ProtoMessage()    {}
func (*EmojiChat_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{25}
}

func (m *EmojiChat_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_S2C.Unmarshal(m, b)
}
func (m *EmojiChat_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_S2C.Marshal(b, m, deterministic)
}
func (m *EmojiChat_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_S2C.Merge(m, src)
}
func (m *EmojiChat_S2C) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_S2C.Size(m)
}
func (m *EmojiChat_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_S2C proto.InternalMessageInfo

func (m *EmojiChat_S2C) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_S2C) GetActId() string {
	if m != nil {
		return m.ActId
	}
	return ""
}

func (m *EmojiChat_S2C) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("msg.GameStep", GameStep_name, GameStep_value)
	proto.RegisterEnum("msg.PlayerStatus", PlayerStatus_name, PlayerStatus_value)
	proto.RegisterEnum("msg.BankerStatus", BankerStatus_name, BankerStatus_value)
	proto.RegisterEnum("msg.PotType", PotType_name, PotType_value)
	proto.RegisterEnum("msg.CardsType", CardsType_name, CardsType_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*Login_C2S)(nil), "msg.Login_C2S")
	proto.RegisterType((*Login_S2C)(nil), "msg.Login_S2C")
	proto.RegisterType((*Logout_C2S)(nil), "msg.Logout_C2S")
	proto.RegisterType((*Logout_S2C)(nil), "msg.Logout_S2C")
	proto.RegisterType((*DownBetMoney)(nil), "msg.DownBetMoney")
	proto.RegisterType((*PotWinList)(nil), "msg.PotWinList")
	proto.RegisterType((*PlayerData)(nil), "msg.PlayerData")
	proto.RegisterType((*RoomData)(nil), "msg.RoomData")
	proto.RegisterType((*JoinRoom_C2S)(nil), "msg.JoinRoom_C2S")
	proto.RegisterType((*JoinRoom_S2C)(nil), "msg.JoinRoom_S2C")
	proto.RegisterType((*EnterRoom_S2C)(nil), "msg.EnterRoom_S2C")
	proto.RegisterType((*LeaveRoom_C2S)(nil), "msg.LeaveRoom_C2S")
	proto.RegisterType((*LeaveRoom_S2C)(nil), "msg.LeaveRoom_S2C")
	proto.RegisterType((*ActionTime_S2C)(nil), "msg.ActionTime_S2C")
	proto.RegisterType((*PlayerAction_C2S)(nil), "msg.PlayerAction_C2S")
	proto.RegisterType((*PlayerAction_S2C)(nil), "msg.PlayerAction_S2C")
	proto.RegisterType((*PotChangeMoney_S2C)(nil), "msg.PotChangeMoney_S2C")
	proto.RegisterType((*UptPlayerList_S2C)(nil), "msg.UptPlayerList_S2C")
	proto.RegisterType((*ResultData_S2C)(nil), "msg.ResultData_S2C")
	proto.RegisterType((*BankerData_C2S)(nil), "msg.BankerData_C2S")
	proto.RegisterType((*BankerData_S2C)(nil), "msg.BankerData_S2C")
	proto.RegisterType((*EmojiChat_C2S)(nil), "msg.EmojiChat_C2S")
	proto.RegisterType((*EmojiChat_S2C)(nil), "msg.EmojiChat_S2C")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 1273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x49, 0x1d, 0x47, 0x07, 0xaf, 0xf7, 0x77, 0x02, 0xfd, 0x41, 0x50, 0x18, 0x44, 0x61,
	0x24, 0xba, 0x48, 0x01, 0x15, 0x45, 0xd1, 0xb4, 0x45, 0x9b, 0xc8, 0x41, 0xa0, 0xc0, 0x0e, 0x04,
	0xca, 0x41, 0x9c, 0x2b, 0x63, 0x2d, 0x6d, 0x69, 0xd6, 0x12, 0x57, 0x20, 0x57, 0x36, 0x8c, 0xbe,
	0x44, 0xd1, 0xcb, 0x5e, 0xf6, 0xc5, 0xfa, 0x12, 0x7d, 0x80, 0x62, 0xf6, 0x40, 0x2d, 0x65, 0x3b,
	0x8d, 0x73, 0xa7, 0xef, 0x9b, 0x6f, 0x67, 0x77, 0x0e, 0x3b, 0x5c, 0x41, 0x73, 0x91, 0xc7, 0xcf,
	0x96, 0x99, 0x90, 0x82, 0x06, 0x8b, 0x3c, 0x0e, 0x6b, 0x50, 0x19, 0x27, 0x69, 0x1c, 0xee, 0x43,
	0x65, 0x2c, 0xd2, 0x98, 0x7e, 0x01, 0x90, 0xf3, 0xec, 0x92, 0x67, 0xc7, 0xc9, 0x82, 0xf7, 0xbc,
	0x3d, 0xef, 0x49, 0x10, 0x39, 0x4c, 0x38, 0x07, 0x18, 0xcf, 0xd9, 0x35, 0xcf, 0x46, 0xe9, 0x2f,
	0x82, 0x76, 0xc1, 0x1f, 0xcd, 0x94, 0xaa, 0x19, 0xf9, 0xa3, 0x19, 0x7d, 0x04, 0x8d, 0x34, 0x99,
	0x5e, 0xbc, 0x65, 0x0b, 0xde, 0xf3, 0x15, 0x5b, 0x60, 0xda, 0x83, 0xfa, 0x39, 0x67, 0xb3, 0xd1,
	0x22, 0xee, 0x05, 0xca, 0x64, 0x21, 0x5a, 0xd8, 0x74, 0x2a, 0x56, 0xa9, 0xec, 0x55, 0xf6, 0xbc,
	0x27, 0x5e, 0x64, 0x61, 0x78, 0x04, 0xcd, 0x43, 0x11, 0x27, 0xe9, 0xe9, 0x70, 0x30, 0xb9, 0x6d,
	0xb3, 0x31, 0xcb, 0xf3, 0xf7, 0x22, 0x9b, 0xd9, 0xcd, 0x2c, 0xa6, 0xbb, 0x50, 0x3d, 0x16, 0x17,
	0x3c, 0x35, 0x5b, 0x69, 0x10, 0x5e, 0x5a, 0x77, 0x93, 0xc1, 0x90, 0x7e, 0x05, 0xb0, 0x2c, 0x22,
	0x51, 0x6e, 0x5b, 0x83, 0xed, 0x67, 0x98, 0x9e, 0x75, 0x80, 0x91, 0x23, 0xc1, 0xfd, 0xce, 0xd8,
	0xf4, 0x22, 0x13, 0x62, 0xa1, 0xf6, 0x6b, 0x44, 0x05, 0xa6, 0x8f, 0xa1, 0xa9, 0x57, 0xbd, 0x5d,
	0x2d, 0xd4, 0x9e, 0xd5, 0x68, 0x4d, 0x84, 0x6d, 0x80, 0x43, 0x11, 0x8b, 0x95, 0xc4, 0x38, 0x1c,
	0x34, 0x19, 0x0c, 0xc3, 0x3f, 0x7c, 0x68, 0x1f, 0x88, 0xab, 0xf4, 0x25, 0x97, 0x47, 0x22, 0xe5,
	0xd7, 0x58, 0x81, 0x97, 0x49, 0x6c, 0x28, 0x75, 0xae, 0x6a, 0xe4, 0x30, 0x34, 0x84, 0xf6, 0x64,
	0xc1, 0xe6, 0x73, 0xab, 0xf0, 0x95, 0xa2, 0xc4, 0xd1, 0x2f, 0xa1, 0x33, 0x49, 0xd2, 0x78, 0xce,
	0xad, 0x48, 0x1f, 0xa9, 0x4c, 0xa2, 0xea, 0x40, 0xac, 0xce, 0xd6, 0xaa, 0x8a, 0x56, 0x95, 0x48,
	0xba, 0x07, 0xad, 0x31, 0x4b, 0x32, 0xab, 0xa9, 0x2a, 0x8d, 0x4b, 0xd1, 0x27, 0xb0, 0x3d, 0x91,
	0x19, 0x4b, 0xe2, 0x73, 0x69, 0x55, 0x35, 0xa5, 0xda, 0xa4, 0xe9, 0x3e, 0x74, 0x0f, 0xb9, 0x58,
	0xb2, 0x6c, 0x66, 0x85, 0x75, 0x25, 0xdc, 0x60, 0xc3, 0xdf, 0x3d, 0x80, 0xb1, 0x90, 0xef, 0x93,
	0xf4, 0x30, 0xc9, 0x25, 0x66, 0x37, 0xe3, 0xf9, 0x6a, 0x2e, 0x31, 0xbb, 0x3a, 0x23, 0x6b, 0x42,
	0xd5, 0x25, 0x89, 0x55, 0xfc, 0x26, 0x19, 0x05, 0xc6, 0x95, 0x79, 0x92, 0xea, 0x80, 0x6c, 0x5d,
	0x0a, 0x82, 0xf6, 0xa1, 0x31, 0x65, 0xd9, 0xec, 0xf8, 0x7a, 0xc9, 0x55, 0xec, 0xdd, 0x41, 0x57,
	0x35, 0xc0, 0x90, 0x65, 0xb3, 0x1c, 0xd9, 0xa8, 0xb0, 0x87, 0xff, 0xf8, 0xb6, 0xf3, 0x0f, 0x98,
	0x64, 0xf7, 0xef, 0x9e, 0x6f, 0xa0, 0x3d, 0x73, 0xca, 0xac, 0x4e, 0xda, 0x1a, 0xec, 0xa8, 0x25,
	0x6e, 0xfd, 0xa3, 0x92, 0x8c, 0x3e, 0x85, 0x5a, 0x2e, 0x99, 0x5c, 0xe5, 0xea, 0xf4, 0x5d, 0xb3,
	0x40, 0xef, 0x31, 0x51, 0x86, 0xc8, 0x08, 0xb0, 0x31, 0xa4, 0x90, 0x6c, 0x5e, 0xae, 0x66, 0x89,
	0xc3, 0x92, 0x5f, 0x25, 0xe9, 0x31, 0x52, 0x43, 0x75, 0xe1, 0x74, 0x39, 0xcb, 0x24, 0x96, 0x5c,
	0xa7, 0x57, 0x1f, 0xb5, 0xa6, 0x2e, 0xa5, 0x4b, 0xa9, 0xf0, 0x8b, 0xfa, 0xf4, 0xea, 0x7b, 0xc1,
	0x3a, 0xfc, 0x82, 0x8e, 0x1c, 0x09, 0x16, 0x69, 0x94, 0xbf, 0x98, 0xca, 0x44, 0xa4, 0xbd, 0x86,
	0xbe, 0x3c, 0x16, 0x6b, 0xdb, 0x4b, 0x96, 0x5e, 0xf0, 0xac, 0xd7, 0xb4, 0x36, 0x8d, 0xc3, 0xbf,
	0x7c, 0x68, 0x44, 0x42, 0x2c, 0x54, 0xd2, 0x1f, 0x42, 0x0d, 0x6f, 0x5b, 0x31, 0x05, 0x0c, 0x5a,
	0x17, 0x03, 0x55, 0x3d, 0xdf, 0x3d, 0x4d, 0x41, 0x47, 0x8e, 0x04, 0x77, 0x8c, 0xd9, 0x82, 0xab,
	0x19, 0xa7, 0xbb, 0xa2, 0xc0, 0xf4, 0xa9, 0xb6, 0x4d, 0x24, 0x5f, 0x9a, 0xa6, 0xe8, 0x28, 0x57,
	0xaf, 0x0d, 0x19, 0x15, 0xe6, 0x75, 0x5f, 0x8e, 0x54, 0x26, 0x83, 0x75, 0x5f, 0x8e, 0x52, 0x49,
	0xbf, 0x85, 0xce, 0x52, 0xe8, 0x7c, 0xe9, 0x5c, 0xd7, 0xee, 0x2a, 0x79, 0x59, 0x77, 0xef, 0xe4,
	0x86, 0xfb, 0xd0, 0x7e, 0x23, 0x92, 0x14, 0xf3, 0xa4, 0x26, 0xe5, 0x1d, 0x79, 0x0a, 0xbf, 0x73,
	0x74, 0x38, 0x02, 0x9f, 0x42, 0x23, 0x33, 0xb9, 0x35, 0x2d, 0xac, 0x43, 0xb5, 0x09, 0x8f, 0x0a,
	0x73, 0xf8, 0x1c, 0x3a, 0xaf, 0x52, 0xc9, 0xb3, 0xcf, 0x59, 0xbb, 0x0d, 0x9d, 0x43, 0xce, 0x2e,
	0xb9, 0x3d, 0x5f, 0xf8, 0xb3, 0x4b, 0x7c, 0xce, 0x2c, 0x0e, 0x3f, 0x40, 0x57, 0x37, 0x0f, 0x96,
	0x4c, 0xb9, 0xc0, 0x9b, 0x2e, 0x59, 0x26, 0x8b, 0xef, 0x16, 0xde, 0x74, 0x4b, 0x94, 0x8a, 0xea,
	0x7f, 0xb4, 0xa8, 0xe1, 0x12, 0x88, 0xde, 0x54, 0x6f, 0xa0, 0x12, 0xda, 0x83, 0xfa, 0xac, 0x34,
	0x90, 0x2d, 0xa4, 0xfb, 0xda, 0x32, 0x16, 0xd2, 0xf8, 0x6d, 0xdb, 0x42, 0xa9, 0xf9, 0x61, 0x8d,
	0xa5, 0xfe, 0x0f, 0xca, 0xfd, 0x1f, 0xfe, 0xe9, 0x6d, 0x6c, 0x89, 0xf1, 0x6c, 0x7e, 0xed, 0x9c,
	0x23, 0xf8, 0x77, 0x1e, 0x21, 0xf8, 0xd4, 0x23, 0x54, 0x36, 0xae, 0xa0, 0xf3, 0x09, 0xae, 0x6e,
	0x7e, 0x82, 0xe9, 0x58, 0xc8, 0xe1, 0x39, 0x4b, 0x63, 0xae, 0x7a, 0x54, 0x9d, 0xee, 0x46, 0x6f,
	0x7b, 0x9f, 0xd6, 0xdb, 0xe1, 0x01, 0xec, 0xbc, 0x5b, 0x4a, 0x1d, 0x2d, 0xf6, 0x6e, 0xb9, 0xfc,
	0xaa, 0xe1, 0xbd, 0x8f, 0xde, 0x5f, 0xd5, 0xf0, 0xdf, 0x43, 0x37, 0x52, 0xf7, 0x0c, 0x2d, 0xf7,
	0x6d, 0xc7, 0x0f, 0xd0, 0xd5, 0xc3, 0x45, 0x2d, 0xc6, 0xf2, 0xae, 0x87, 0xac, 0xe7, 0x0c, 0x59,
	0x2d, 0xda, 0x18, 0xb2, 0x8f, 0xa1, 0x29, 0xd9, 0x05, 0x5f, 0xcf, 0xf0, 0x6a, 0xb4, 0x26, 0xc2,
	0x17, 0x25, 0xd7, 0xb7, 0x85, 0xe6, 0xfd, 0x57, 0x68, 0x3f, 0x41, 0xe7, 0xd5, 0x42, 0xfc, 0x9a,
	0x0c, 0xcf, 0x99, 0xb4, 0x97, 0x99, 0x4d, 0x9d, 0x2f, 0x9f, 0x41, 0xc8, 0xc7, 0x82, 0xcd, 0x47,
	0xf6, 0xf1, 0x63, 0x50, 0xf8, 0xce, 0x75, 0x80, 0x47, 0xb8, 0xcb, 0xc1, 0x2e, 0x54, 0xd9, 0x54,
	0x16, 0xeb, 0x35, 0x70, 0xdc, 0x06, 0xae, 0xdb, 0xfe, 0xdf, 0x01, 0x34, 0x8f, 0x78, 0x9e, 0xb3,
	0x98, 0x8f, 0x0e, 0x68, 0x1b, 0x1a, 0x47, 0x93, 0xd7, 0xa7, 0xf8, 0x74, 0x24, 0x5b, 0x05, 0x12,
	0x69, 0x4c, 0x3c, 0xba, 0x03, 0x1d, 0x44, 0xc5, 0xc3, 0x8d, 0xf8, 0x65, 0x6a, 0x32, 0x18, 0x92,
	0x80, 0x52, 0xe8, 0x1a, 0xca, 0xbc, 0x8b, 0x48, 0x65, 0x83, 0x43, 0x5d, 0x95, 0xee, 0x02, 0x41,
	0xce, 0x9d, 0x6f, 0xa4, 0x76, 0x83, 0x45, 0x6d, 0x9d, 0x3e, 0x80, 0x1d, 0x64, 0x4b, 0x83, 0x8a,
	0x34, 0x2c, 0x5d, 0x9a, 0x41, 0xa4, 0x79, 0x93, 0x46, 0x35, 0xd0, 0x87, 0x40, 0x91, 0x2e, 0x8f,
	0x17, 0xd2, 0xa2, 0x3d, 0xd8, 0x55, 0x41, 0x6e, 0xcc, 0x06, 0xd2, 0xbe, 0xd5, 0x82, 0x6b, 0x3a,
	0xf4, 0x11, 0x3c, 0xd4, 0x89, 0xd9, 0xbc, 0x40, 0xa4, 0x4b, 0xff, 0x0f, 0x0f, 0xd0, 0x76, 0xe3,
	0x36, 0x90, 0x6d, 0x7b, 0x84, 0x72, 0x8b, 0x13, 0x62, 0xf9, 0x72, 0xf7, 0x92, 0x9d, 0x5b, 0x78,
	0xd4, 0xd3, 0x22, 0x1f, 0x6e, 0x3f, 0x91, 0xff, 0xdd, 0xa4, 0x51, 0xbd, 0xdb, 0xff, 0x01, 0x1a,
	0x76, 0x1c, 0xd2, 0x16, 0xd4, 0x4f, 0x4e, 0x4e, 0xf1, 0x27, 0xd9, 0xa2, 0x00, 0x35, 0xed, 0x9a,
	0x78, 0x68, 0x30, 0xd7, 0x9b, 0xf8, 0x68, 0x98, 0x70, 0x29, 0xe7, 0x9c, 0x04, 0xfd, 0xe7, 0xd0,
	0x76, 0x5f, 0x25, 0xb4, 0x03, 0x4d, 0xe5, 0x01, 0x81, 0x6e, 0x11, 0x34, 0xe3, 0x06, 0xc4, 0x43,
	0xe3, 0x7b, 0x26, 0xa7, 0xe7, 0x0a, 0xfa, 0xfd, 0x37, 0xd0, 0x76, 0x2f, 0x1b, 0x9a, 0x35, 0x7e,
	0x2b, 0x24, 0xd9, 0x72, 0xe1, 0x15, 0xf1, 0xd0, 0x95, 0x86, 0xef, 0x96, 0xc4, 0xa7, 0x5d, 0x00,
	0x13, 0xb7, 0xb8, 0x4a, 0x49, 0xd0, 0xff, 0x0d, 0xea, 0x66, 0xf2, 0xe1, 0xf1, 0x4e, 0x4e, 0x30,
	0xf9, 0x26, 0x86, 0x24, 0xc6, 0xdf, 0xca, 0x81, 0x7a, 0x1d, 0x22, 0xf2, 0xd1, 0xbb, 0x7e, 0x16,
	0x23, 0x0c, 0x10, 0xea, 0xd7, 0x21, 0xc2, 0x0a, 0xc6, 0x8b, 0x4f, 0x5d, 0x04, 0x55, 0xba, 0x0d,
	0x2d, 0xfb, 0xa2, 0x45, 0xa2, 0x86, 0x9b, 0x9b, 0x97, 0x2b, 0xe2, 0x7a, 0xff, 0x47, 0x68, 0x16,
	0x6f, 0x47, 0x93, 0x43, 0xc4, 0x64, 0x8b, 0x36, 0xa0, 0x82, 0x7e, 0xcc, 0xee, 0xc6, 0x09, 0xf1,
	0x51, 0x64, 0x3c, 0x90, 0xe0, 0xac, 0xa6, 0xfe, 0x98, 0x7d, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4b, 0x36, 0xf7, 0x4d, 0xa5, 0x0d, 0x00, 0x00,
}
