// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息ID
type MessageID int32

const (
	MessageID_MSG_Ping                   MessageID = 0
	MessageID_MSG_Pong                   MessageID = 1
	MessageID_MSG_Login_C2S              MessageID = 2
	MessageID_MSG_Login_S2C              MessageID = 3
	MessageID_MSG_Logout_C2S             MessageID = 4
	MessageID_MSG_Logout_S2C             MessageID = 5
	MessageID_MSG_JoinRoom_C2S           MessageID = 6
	MessageID_MSG_JoinRoom_S2C           MessageID = 7
	MessageID_MSG_EnterRoom_S2C          MessageID = 8
	MessageID_MSG_LeaveRoom_C2S          MessageID = 9
	MessageID_MSG_LeaveRoom_S2C          MessageID = 10
	MessageID_MSG_ActionTime_S2C         MessageID = 11
	MessageID_MSG_PlayerAction_C2S       MessageID = 12
	MessageID_MSG_PlayerAction_S2C       MessageID = 13
	MessageID_MSG_PotChangeMoney_S2C     MessageID = 14
	MessageID_MSG_ResultData_S2C         MessageID = 15
	MessageID_MSG_BankerData_C2S         MessageID = 16
	MessageID_MSG_BankerData_S2C         MessageID = 17
	MessageID_MSG_EmojiChat_C2S          MessageID = 18
	MessageID_MSG_EmojiChat_S2C          MessageID = 19
	MessageID_MSG_SendActTime_S2C        MessageID = 20
	MessageID_MSG_ChangeRoomType_S2C     MessageID = 21
	MessageID_MSG_ErrorMsg_S2C           MessageID = 22
	MessageID_MSG_ShowTableInfo_C2S      MessageID = 23
	MessageID_MSG_ShowTableInfo_S2C      MessageID = 24
	MessageID_MSG_KickedOutPush          MessageID = 25
	MessageID_MSG_ZhiBoUpdateBalancePush MessageID = 26
)

var MessageID_name = map[int32]string{
	0:  "MSG_Ping",
	1:  "MSG_Pong",
	2:  "MSG_Login_C2S",
	3:  "MSG_Login_S2C",
	4:  "MSG_Logout_C2S",
	5:  "MSG_Logout_S2C",
	6:  "MSG_JoinRoom_C2S",
	7:  "MSG_JoinRoom_S2C",
	8:  "MSG_EnterRoom_S2C",
	9:  "MSG_LeaveRoom_C2S",
	10: "MSG_LeaveRoom_S2C",
	11: "MSG_ActionTime_S2C",
	12: "MSG_PlayerAction_C2S",
	13: "MSG_PlayerAction_S2C",
	14: "MSG_PotChangeMoney_S2C",
	15: "MSG_ResultData_S2C",
	16: "MSG_BankerData_C2S",
	17: "MSG_BankerData_S2C",
	18: "MSG_EmojiChat_C2S",
	19: "MSG_EmojiChat_S2C",
	20: "MSG_SendActTime_S2C",
	21: "MSG_ChangeRoomType_S2C",
	22: "MSG_ErrorMsg_S2C",
	23: "MSG_ShowTableInfo_C2S",
	24: "MSG_ShowTableInfo_S2C",
	25: "MSG_KickedOutPush",
	26: "MSG_ZhiBoUpdateBalancePush",
}

var MessageID_value = map[string]int32{
	"MSG_Ping":                   0,
	"MSG_Pong":                   1,
	"MSG_Login_C2S":              2,
	"MSG_Login_S2C":              3,
	"MSG_Logout_C2S":             4,
	"MSG_Logout_S2C":             5,
	"MSG_JoinRoom_C2S":           6,
	"MSG_JoinRoom_S2C":           7,
	"MSG_EnterRoom_S2C":          8,
	"MSG_LeaveRoom_C2S":          9,
	"MSG_LeaveRoom_S2C":          10,
	"MSG_ActionTime_S2C":         11,
	"MSG_PlayerAction_C2S":       12,
	"MSG_PlayerAction_S2C":       13,
	"MSG_PotChangeMoney_S2C":     14,
	"MSG_ResultData_S2C":         15,
	"MSG_BankerData_C2S":         16,
	"MSG_BankerData_S2C":         17,
	"MSG_EmojiChat_C2S":          18,
	"MSG_EmojiChat_S2C":          19,
	"MSG_SendActTime_S2C":        20,
	"MSG_ChangeRoomType_S2C":     21,
	"MSG_ErrorMsg_S2C":           22,
	"MSG_ShowTableInfo_C2S":      23,
	"MSG_ShowTableInfo_S2C":      24,
	"MSG_KickedOutPush":          25,
	"MSG_ZhiBoUpdateBalancePush": 26,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

// 游戏阶段
type GameStep int32

const (
	GameStep_XX_Step GameStep = 0
	GameStep_Banker  GameStep = 1
	GameStep_Banker2 GameStep = 2
	GameStep_DownBet GameStep = 3
	GameStep_Settle  GameStep = 4
	GameStep_Close   GameStep = 5
	GameStep_GetRes  GameStep = 6
	GameStep_LiuJu   GameStep = 7
)

var GameStep_name = map[int32]string{
	0: "XX_Step",
	1: "Banker",
	2: "Banker2",
	3: "DownBet",
	4: "Settle",
	5: "Close",
	6: "GetRes",
	7: "LiuJu",
}

var GameStep_value = map[string]int32{
	"XX_Step": 0,
	"Banker":  1,
	"Banker2": 2,
	"DownBet": 3,
	"Settle":  4,
	"Close":   5,
	"GetRes":  6,
	"LiuJu":   7,
}

func (x GameStep) String() string {
	return proto.EnumName(GameStep_name, int32(x))
}

func (GameStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

type PlayerStatus int32

const (
	PlayerStatus_XX_Status PlayerStatus = 0
	PlayerStatus_PlayGame  PlayerStatus = 1
	PlayerStatus_WatchGame PlayerStatus = 2
)

var PlayerStatus_name = map[int32]string{
	0: "XX_Status",
	1: "PlayGame",
	2: "WatchGame",
}

var PlayerStatus_value = map[string]int32{
	"XX_Status": 0,
	"PlayGame":  1,
	"WatchGame": 2,
}

func (x PlayerStatus) String() string {
	return proto.EnumName(PlayerStatus_name, int32(x))
}

func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

type BankerStatus int32

const (
	BankerStatus_BankerNot  BankerStatus = 0
	BankerStatus_BankerUp   BankerStatus = 1
	BankerStatus_BankerDown BankerStatus = 2
)

var BankerStatus_name = map[int32]string{
	0: "BankerNot",
	1: "BankerUp",
	2: "BankerDown",
}

var BankerStatus_value = map[string]int32{
	"BankerNot":  0,
	"BankerUp":   1,
	"BankerDown": 2,
}

func (x BankerStatus) String() string {
	return proto.EnumName(BankerStatus_name, int32(x))
}

func (BankerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

//注池类型
type PotType int32

const (
	PotType_XX_Pot      PotType = 0
	PotType_BigPot      PotType = 1
	PotType_SmallPot    PotType = 2
	PotType_SinglePot   PotType = 3
	PotType_DoublePot   PotType = 4
	PotType_PairPot     PotType = 5
	PotType_StraightPot PotType = 6
	PotType_LeopardPot  PotType = 7
)

var PotType_name = map[int32]string{
	0: "XX_Pot",
	1: "BigPot",
	2: "SmallPot",
	3: "SinglePot",
	4: "DoublePot",
	5: "PairPot",
	6: "StraightPot",
	7: "LeopardPot",
}

var PotType_value = map[string]int32{
	"XX_Pot":      0,
	"BigPot":      1,
	"SmallPot":    2,
	"SinglePot":   3,
	"DoublePot":   4,
	"PairPot":     5,
	"StraightPot": 6,
	"LeopardPot":  7,
}

func (x PotType) String() string {
	return proto.EnumName(PotType_name, int32(x))
}

func (PotType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

//卡牌类型
type CardsType int32

const (
	CardsType_XX_Card CardsType = 0
	CardsType_Small   CardsType = 1
	CardsType_Big     CardsType = 2
	CardsType_Leopard CardsType = 3
)

var CardsType_name = map[int32]string{
	0: "XX_Card",
	1: "Small",
	2: "Big",
	3: "Leopard",
}

var CardsType_value = map[string]int32{
	"XX_Card": 0,
	"Small":   1,
	"Big":     2,
	"Leopard": 3,
}

func (x CardsType) String() string {
	return proto.EnumName(CardsType_name, int32(x))
}

func (CardsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Account              float64  `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

type Login_C2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C2S) Reset()         { *m = Login_C2S{} }
func (m *Login_C2S) String() string { return proto.CompactTextString(m) }
func (*Login_C2S) ProtoMessage()    {}
func (*Login_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Login_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C2S.Unmarshal(m, b)
}
func (m *Login_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C2S.Marshal(b, m, deterministic)
}
func (m *Login_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C2S.Merge(m, src)
}
func (m *Login_C2S) XXX_Size() int {
	return xxx_messageInfo_Login_C2S.Size(m)
}
func (m *Login_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C2S proto.InternalMessageInfo

func (m *Login_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Login_C2S) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *Login_C2S) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Login_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	Backroom             bool        `protobuf:"varint,2,opt,name=backroom,proto3" json:"backroom,omitempty"`
	PlayerNumR1          int32       `protobuf:"varint,3,opt,name=PlayerNumR1,proto3" json:"PlayerNumR1,omitempty"`
	PlayerNumR2          int32       `protobuf:"varint,4,opt,name=PlayerNumR2,proto3" json:"PlayerNumR2,omitempty"`
	Room01               bool        `protobuf:"varint,5,opt,name=room01,proto3" json:"room01,omitempty"`
	Room02               bool        `protobuf:"varint,6,opt,name=room02,proto3" json:"room02,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Login_S2C) Reset()         { *m = Login_S2C{} }
func (m *Login_S2C) String() string { return proto.CompactTextString(m) }
func (*Login_S2C) ProtoMessage()    {}
func (*Login_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Login_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S2C.Unmarshal(m, b)
}
func (m *Login_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S2C.Marshal(b, m, deterministic)
}
func (m *Login_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S2C.Merge(m, src)
}
func (m *Login_S2C) XXX_Size() int {
	return xxx_messageInfo_Login_S2C.Size(m)
}
func (m *Login_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S2C proto.InternalMessageInfo

func (m *Login_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Login_S2C) GetBackroom() bool {
	if m != nil {
		return m.Backroom
	}
	return false
}

func (m *Login_S2C) GetPlayerNumR1() int32 {
	if m != nil {
		return m.PlayerNumR1
	}
	return 0
}

func (m *Login_S2C) GetPlayerNumR2() int32 {
	if m != nil {
		return m.PlayerNumR2
	}
	return 0
}

func (m *Login_S2C) GetRoom01() bool {
	if m != nil {
		return m.Room01
	}
	return false
}

func (m *Login_S2C) GetRoom02() bool {
	if m != nil {
		return m.Room02
	}
	return false
}

type Logout_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_C2S) Reset()         { *m = Logout_C2S{} }
func (m *Logout_C2S) String() string { return proto.CompactTextString(m) }
func (*Logout_C2S) ProtoMessage()    {}
func (*Logout_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Logout_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_C2S.Unmarshal(m, b)
}
func (m *Logout_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_C2S.Marshal(b, m, deterministic)
}
func (m *Logout_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_C2S.Merge(m, src)
}
func (m *Logout_C2S) XXX_Size() int {
	return xxx_messageInfo_Logout_C2S.Size(m)
}
func (m *Logout_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_C2S proto.InternalMessageInfo

type Logout_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout_S2C) Reset()         { *m = Logout_S2C{} }
func (m *Logout_S2C) String() string { return proto.CompactTextString(m) }
func (*Logout_S2C) ProtoMessage()    {}
func (*Logout_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Logout_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout_S2C.Unmarshal(m, b)
}
func (m *Logout_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout_S2C.Marshal(b, m, deterministic)
}
func (m *Logout_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout_S2C.Merge(m, src)
}
func (m *Logout_S2C) XXX_Size() int {
	return xxx_messageInfo_Logout_S2C.Size(m)
}
func (m *Logout_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_Logout_S2C proto.InternalMessageInfo

type PotWinList struct {
	ResultNum            int32     `protobuf:"varint,1,opt,name=resultNum,proto3" json:"resultNum,omitempty"`
	BigSmall             int32     `protobuf:"varint,2,opt,name=bigSmall,proto3" json:"bigSmall,omitempty"`
	SinDouble            int32     `protobuf:"varint,3,opt,name=sinDouble,proto3" json:"sinDouble,omitempty"`
	CardType             CardsType `protobuf:"varint,4,opt,name=cardType,proto3,enum=msg.CardsType" json:"cardType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PotWinList) Reset()         { *m = PotWinList{} }
func (m *PotWinList) String() string { return proto.CompactTextString(m) }
func (*PotWinList) ProtoMessage()    {}
func (*PotWinList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *PotWinList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotWinList.Unmarshal(m, b)
}
func (m *PotWinList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotWinList.Marshal(b, m, deterministic)
}
func (m *PotWinList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotWinList.Merge(m, src)
}
func (m *PotWinList) XXX_Size() int {
	return xxx_messageInfo_PotWinList.Size(m)
}
func (m *PotWinList) XXX_DiscardUnknown() {
	xxx_messageInfo_PotWinList.DiscardUnknown(m)
}

var xxx_messageInfo_PotWinList proto.InternalMessageInfo

func (m *PotWinList) GetResultNum() int32 {
	if m != nil {
		return m.ResultNum
	}
	return 0
}

func (m *PotWinList) GetBigSmall() int32 {
	if m != nil {
		return m.BigSmall
	}
	return 0
}

func (m *PotWinList) GetSinDouble() int32 {
	if m != nil {
		return m.SinDouble
	}
	return 0
}

func (m *PotWinList) GetCardType() CardsType {
	if m != nil {
		return m.CardType
	}
	return CardsType_XX_Card
}

type PlayerData struct {
	PlayerInfo           *PlayerInfo       `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	DownBetMoney         *DownBetMoney     `protobuf:"bytes,2,opt,name=downBetMoney,proto3" json:"downBetMoney,omitempty"`
	Status               PlayerStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=msg.PlayerStatus" json:"status,omitempty"`
	BankerMoney          float64           `protobuf:"fixed64,4,opt,name=bankerMoney,proto3" json:"bankerMoney,omitempty"`
	BankerCount          int32             `protobuf:"varint,5,opt,name=bankerCount,proto3" json:"bankerCount,omitempty"`
	TotalDownBet         int32             `protobuf:"varint,6,opt,name=totalDownBet,proto3" json:"totalDownBet,omitempty"`
	WinTotalCount        int32             `protobuf:"varint,7,opt,name=winTotalCount,proto3" json:"winTotalCount,omitempty"`
	ResultMoney          float64           `protobuf:"fixed64,8,opt,name=resultMoney,proto3" json:"resultMoney,omitempty"`
	DownBetHistory       []*DownBetHistory `protobuf:"bytes,10,rep,name=downBetHistory,proto3" json:"downBetHistory,omitempty"`
	IsAction             bool              `protobuf:"varint,11,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	IsBanker             bool              `protobuf:"varint,12,opt,name=IsBanker,proto3" json:"IsBanker,omitempty"`
	IsRobot              bool              `protobuf:"varint,13,opt,name=IsRobot,proto3" json:"IsRobot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetDownBetMoney() *DownBetMoney {
	if m != nil {
		return m.DownBetMoney
	}
	return nil
}

func (m *PlayerData) GetStatus() PlayerStatus {
	if m != nil {
		return m.Status
	}
	return PlayerStatus_XX_Status
}

func (m *PlayerData) GetBankerMoney() float64 {
	if m != nil {
		return m.BankerMoney
	}
	return 0
}

func (m *PlayerData) GetBankerCount() int32 {
	if m != nil {
		return m.BankerCount
	}
	return 0
}

func (m *PlayerData) GetTotalDownBet() int32 {
	if m != nil {
		return m.TotalDownBet
	}
	return 0
}

func (m *PlayerData) GetWinTotalCount() int32 {
	if m != nil {
		return m.WinTotalCount
	}
	return 0
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil {
		return m.ResultMoney
	}
	return 0
}

func (m *PlayerData) GetDownBetHistory() []*DownBetHistory {
	if m != nil {
		return m.DownBetHistory
	}
	return nil
}

func (m *PlayerData) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerData) GetIsBanker() bool {
	if m != nil {
		return m.IsBanker
	}
	return false
}

func (m *PlayerData) GetIsRobot() bool {
	if m != nil {
		return m.IsRobot
	}
	return false
}

//玩家各注池下注的金额
type DownBetMoney struct {
	BigDownBet           int32    `protobuf:"varint,1,opt,name=BigDownBet,proto3" json:"BigDownBet,omitempty"`
	SmallDownBet         int32    `protobuf:"varint,2,opt,name=SmallDownBet,proto3" json:"SmallDownBet,omitempty"`
	SingleDownBet        int32    `protobuf:"varint,3,opt,name=SingleDownBet,proto3" json:"SingleDownBet,omitempty"`
	DoubleDownBet        int32    `protobuf:"varint,4,opt,name=DoubleDownBet,proto3" json:"DoubleDownBet,omitempty"`
	PairDownBet          int32    `protobuf:"varint,5,opt,name=PairDownBet,proto3" json:"PairDownBet,omitempty"`
	StraightDownBet      int32    `protobuf:"varint,6,opt,name=StraightDownBet,proto3" json:"StraightDownBet,omitempty"`
	LeopardDownBet       int32    `protobuf:"varint,7,opt,name=LeopardDownBet,proto3" json:"LeopardDownBet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownBetMoney) Reset()         { *m = DownBetMoney{} }
func (m *DownBetMoney) String() string { return proto.CompactTextString(m) }
func (*DownBetMoney) ProtoMessage()    {}
func (*DownBetMoney) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *DownBetMoney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownBetMoney.Unmarshal(m, b)
}
func (m *DownBetMoney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownBetMoney.Marshal(b, m, deterministic)
}
func (m *DownBetMoney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownBetMoney.Merge(m, src)
}
func (m *DownBetMoney) XXX_Size() int {
	return xxx_messageInfo_DownBetMoney.Size(m)
}
func (m *DownBetMoney) XXX_DiscardUnknown() {
	xxx_messageInfo_DownBetMoney.DiscardUnknown(m)
}

var xxx_messageInfo_DownBetMoney proto.InternalMessageInfo

func (m *DownBetMoney) GetBigDownBet() int32 {
	if m != nil {
		return m.BigDownBet
	}
	return 0
}

func (m *DownBetMoney) GetSmallDownBet() int32 {
	if m != nil {
		return m.SmallDownBet
	}
	return 0
}

func (m *DownBetMoney) GetSingleDownBet() int32 {
	if m != nil {
		return m.SingleDownBet
	}
	return 0
}

func (m *DownBetMoney) GetDoubleDownBet() int32 {
	if m != nil {
		return m.DoubleDownBet
	}
	return 0
}

func (m *DownBetMoney) GetPairDownBet() int32 {
	if m != nil {
		return m.PairDownBet
	}
	return 0
}

func (m *DownBetMoney) GetStraightDownBet() int32 {
	if m != nil {
		return m.StraightDownBet
	}
	return 0
}

func (m *DownBetMoney) GetLeopardDownBet() int32 {
	if m != nil {
		return m.LeopardDownBet
	}
	return 0
}

type DownBetHistory struct {
	TimeFmt              string           `protobuf:"bytes,1,opt,name=timeFmt,proto3" json:"timeFmt,omitempty"`
	ResNum               []int32          `protobuf:"varint,2,rep,packed,name=resNum,proto3" json:"resNum,omitempty"`
	Result               *LotteryResult   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ResultFX             *LotteryResultFX `protobuf:"bytes,4,opt,name=resultFX,proto3" json:"resultFX,omitempty"`
	DownBetMoney         *DownBetMoney    `protobuf:"bytes,5,opt,name=downBetMoney,proto3" json:"downBetMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DownBetHistory) Reset()         { *m = DownBetHistory{} }
func (m *DownBetHistory) String() string { return proto.CompactTextString(m) }
func (*DownBetHistory) ProtoMessage()    {}
func (*DownBetHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{10}
}

func (m *DownBetHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownBetHistory.Unmarshal(m, b)
}
func (m *DownBetHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownBetHistory.Marshal(b, m, deterministic)
}
func (m *DownBetHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownBetHistory.Merge(m, src)
}
func (m *DownBetHistory) XXX_Size() int {
	return xxx_messageInfo_DownBetHistory.Size(m)
}
func (m *DownBetHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_DownBetHistory.DiscardUnknown(m)
}

var xxx_messageInfo_DownBetHistory proto.InternalMessageInfo

func (m *DownBetHistory) GetTimeFmt() string {
	if m != nil {
		return m.TimeFmt
	}
	return ""
}

func (m *DownBetHistory) GetResNum() []int32 {
	if m != nil {
		return m.ResNum
	}
	return nil
}

func (m *DownBetHistory) GetResult() *LotteryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DownBetHistory) GetResultFX() *LotteryResultFX {
	if m != nil {
		return m.ResultFX
	}
	return nil
}

func (m *DownBetHistory) GetDownBetMoney() *DownBetMoney {
	if m != nil {
		return m.DownBetMoney
	}
	return nil
}

// 一般公式結果
type LotteryResult struct {
	LuckyNum             int32     `protobuf:"varint,1,opt,name=luckyNum,proto3" json:"luckyNum,omitempty"`
	CardType             CardsType `protobuf:"varint,2,opt,name=cardType,proto3,enum=msg.CardsType" json:"cardType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LotteryResult) Reset()         { *m = LotteryResult{} }
func (m *LotteryResult) String() string { return proto.CompactTextString(m) }
func (*LotteryResult) ProtoMessage()    {}
func (*LotteryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{11}
}

func (m *LotteryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryResult.Unmarshal(m, b)
}
func (m *LotteryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryResult.Marshal(b, m, deterministic)
}
func (m *LotteryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryResult.Merge(m, src)
}
func (m *LotteryResult) XXX_Size() int {
	return xxx_messageInfo_LotteryResult.Size(m)
}
func (m *LotteryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryResult.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryResult proto.InternalMessageInfo

func (m *LotteryResult) GetLuckyNum() int32 {
	if m != nil {
		return m.LuckyNum
	}
	return 0
}

func (m *LotteryResult) GetCardType() CardsType {
	if m != nil {
		return m.CardType
	}
	return CardsType_XX_Card
}

// 富鑫II公式結果
type LotteryResultFX struct {
	LuckyNum             int32     `protobuf:"varint,1,opt,name=luckyNum,proto3" json:"luckyNum,omitempty"`
	CardType             CardsType `protobuf:"varint,2,opt,name=cardType,proto3,enum=msg.CardsType" json:"cardType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LotteryResultFX) Reset()         { *m = LotteryResultFX{} }
func (m *LotteryResultFX) String() string { return proto.CompactTextString(m) }
func (*LotteryResultFX) ProtoMessage()    {}
func (*LotteryResultFX) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{12}
}

func (m *LotteryResultFX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryResultFX.Unmarshal(m, b)
}
func (m *LotteryResultFX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryResultFX.Marshal(b, m, deterministic)
}
func (m *LotteryResultFX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryResultFX.Merge(m, src)
}
func (m *LotteryResultFX) XXX_Size() int {
	return xxx_messageInfo_LotteryResultFX.Size(m)
}
func (m *LotteryResultFX) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryResultFX.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryResultFX proto.InternalMessageInfo

func (m *LotteryResultFX) GetLuckyNum() int32 {
	if m != nil {
		return m.LuckyNum
	}
	return 0
}

func (m *LotteryResultFX) GetCardType() CardsType {
	if m != nil {
		return m.CardType
	}
	return CardsType_XX_Card
}

type LotteryData struct {
	TimeFmt              string           `protobuf:"bytes,1,opt,name=timeFmt,proto3" json:"timeFmt,omitempty"`
	ResNum               []int32          `protobuf:"varint,2,rep,packed,name=resNum,proto3" json:"resNum,omitempty"`
	Result               *LotteryResult   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ResultFX             *LotteryResultFX `protobuf:"bytes,4,opt,name=resultFX,proto3" json:"resultFX,omitempty"`
	IsLiuJu              bool             `protobuf:"varint,5,opt,name=IsLiuJu,proto3" json:"IsLiuJu,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LotteryData) Reset()         { *m = LotteryData{} }
func (m *LotteryData) String() string { return proto.CompactTextString(m) }
func (*LotteryData) ProtoMessage()    {}
func (*LotteryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{13}
}

func (m *LotteryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryData.Unmarshal(m, b)
}
func (m *LotteryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryData.Marshal(b, m, deterministic)
}
func (m *LotteryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryData.Merge(m, src)
}
func (m *LotteryData) XXX_Size() int {
	return xxx_messageInfo_LotteryData.Size(m)
}
func (m *LotteryData) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryData.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryData proto.InternalMessageInfo

func (m *LotteryData) GetTimeFmt() string {
	if m != nil {
		return m.TimeFmt
	}
	return ""
}

func (m *LotteryData) GetResNum() []int32 {
	if m != nil {
		return m.ResNum
	}
	return nil
}

func (m *LotteryData) GetResult() *LotteryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LotteryData) GetResultFX() *LotteryResultFX {
	if m != nil {
		return m.ResultFX
	}
	return nil
}

func (m *LotteryData) GetIsLiuJu() bool {
	if m != nil {
		return m.IsLiuJu
	}
	return false
}

type RoomData struct {
	RoomId               string         `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoundId              string         `protobuf:"bytes,2,opt,name=roundId,proto3" json:"roundId,omitempty"`
	PlayerData           []*PlayerData  `protobuf:"bytes,3,rep,name=playerData,proto3" json:"playerData,omitempty"`
	GameTime             int32          `protobuf:"varint,4,opt,name=gameTime,proto3" json:"gameTime,omitempty"`
	GameStep             GameStep       `protobuf:"varint,5,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	ResultInt            []int32        `protobuf:"varint,6,rep,packed,name=resultInt,proto3" json:"resultInt,omitempty"`
	PotMoneyCount        *DownBetMoney  `protobuf:"bytes,7,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	HistoryData          []*LotteryData `protobuf:"bytes,8,rep,name=historyData,proto3" json:"historyData,omitempty"`
	TablePlayer          []*PlayerData  `protobuf:"bytes,9,rep,name=tablePlayer,proto3" json:"tablePlayer,omitempty"`
	PeriodsNum           string         `protobuf:"bytes,10,opt,name=PeriodsNum,proto3" json:"PeriodsNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{14}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetRoundId() string {
	if m != nil {
		return m.RoundId
	}
	return ""
}

func (m *RoomData) GetPlayerData() []*PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *RoomData) GetGameTime() int32 {
	if m != nil {
		return m.GameTime
	}
	return 0
}

func (m *RoomData) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_XX_Step
}

func (m *RoomData) GetResultInt() []int32 {
	if m != nil {
		return m.ResultInt
	}
	return nil
}

func (m *RoomData) GetPotMoneyCount() *DownBetMoney {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

func (m *RoomData) GetHistoryData() []*LotteryData {
	if m != nil {
		return m.HistoryData
	}
	return nil
}

func (m *RoomData) GetTablePlayer() []*PlayerData {
	if m != nil {
		return m.TablePlayer
	}
	return nil
}

func (m *RoomData) GetPeriodsNum() string {
	if m != nil {
		return m.PeriodsNum
	}
	return ""
}

type JoinRoom_C2S struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom_C2S) Reset()         { *m = JoinRoom_C2S{} }
func (m *JoinRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_C2S) ProtoMessage()    {}
func (*JoinRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{15}
}

func (m *JoinRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_C2S.Unmarshal(m, b)
}
func (m *JoinRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_C2S.Marshal(b, m, deterministic)
}
func (m *JoinRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_C2S.Merge(m, src)
}
func (m *JoinRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_C2S.Size(m)
}
func (m *JoinRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_C2S proto.InternalMessageInfo

func (m *JoinRoom_C2S) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type JoinRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	LeftTime             int32     `protobuf:"varint,2,opt,name=leftTime,proto3" json:"leftTime,omitempty"`
	CloseTime            int32     `protobuf:"varint,3,opt,name=closeTime,proto3" json:"closeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoom_S2C) Reset()         { *m = JoinRoom_S2C{} }
func (m *JoinRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_S2C) ProtoMessage()    {}
func (*JoinRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{16}
}

func (m *JoinRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_S2C.Unmarshal(m, b)
}
func (m *JoinRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_S2C.Marshal(b, m, deterministic)
}
func (m *JoinRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_S2C.Merge(m, src)
}
func (m *JoinRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_S2C.Size(m)
}
func (m *JoinRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_S2C proto.InternalMessageInfo

func (m *JoinRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func (m *JoinRoom_S2C) GetLeftTime() int32 {
	if m != nil {
		return m.LeftTime
	}
	return 0
}

func (m *JoinRoom_S2C) GetCloseTime() int32 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

type EnterRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoom_S2C) Reset()         { *m = EnterRoom_S2C{} }
func (m *EnterRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoom_S2C) ProtoMessage()    {}
func (*EnterRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{17}
}

func (m *EnterRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoom_S2C.Unmarshal(m, b)
}
func (m *EnterRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoom_S2C.Marshal(b, m, deterministic)
}
func (m *EnterRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoom_S2C.Merge(m, src)
}
func (m *EnterRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoom_S2C.Size(m)
}
func (m *EnterRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoom_S2C proto.InternalMessageInfo

func (m *EnterRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type LeaveRoom_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom_C2S) Reset()         { *m = LeaveRoom_C2S{} }
func (m *LeaveRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_C2S) ProtoMessage()    {}
func (*LeaveRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{18}
}

func (m *LeaveRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_C2S.Unmarshal(m, b)
}
func (m *LeaveRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_C2S.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_C2S.Merge(m, src)
}
func (m *LeaveRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_C2S.Size(m)
}
func (m *LeaveRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_C2S proto.InternalMessageInfo

type LeaveRoom_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LeaveRoom_S2C) Reset()         { *m = LeaveRoom_S2C{} }
func (m *LeaveRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_S2C) ProtoMessage()    {}
func (*LeaveRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{19}
}

func (m *LeaveRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_S2C.Unmarshal(m, b)
}
func (m *LeaveRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_S2C.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_S2C.Merge(m, src)
}
func (m *LeaveRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_S2C.Size(m)
}
func (m *LeaveRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_S2C proto.InternalMessageInfo

func (m *LeaveRoom_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type ActionTime_S2C struct {
	GameStep             GameStep  `protobuf:"varint,1,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	RoomData             *RoomData `protobuf:"bytes,2,opt,name=roomData,proto3" json:"roomData,omitempty"`
	LeftTime             int32     `protobuf:"varint,3,opt,name=leftTime,proto3" json:"leftTime,omitempty"`
	CloseTime            int32     `protobuf:"varint,4,opt,name=closeTime,proto3" json:"closeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ActionTime_S2C) Reset()         { *m = ActionTime_S2C{} }
func (m *ActionTime_S2C) String() string { return proto.CompactTextString(m) }
func (*ActionTime_S2C) ProtoMessage()    {}
func (*ActionTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{20}
}

func (m *ActionTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionTime_S2C.Unmarshal(m, b)
}
func (m *ActionTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionTime_S2C.Marshal(b, m, deterministic)
}
func (m *ActionTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionTime_S2C.Merge(m, src)
}
func (m *ActionTime_S2C) XXX_Size() int {
	return xxx_messageInfo_ActionTime_S2C.Size(m)
}
func (m *ActionTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ActionTime_S2C proto.InternalMessageInfo

func (m *ActionTime_S2C) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_XX_Step
}

func (m *ActionTime_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func (m *ActionTime_S2C) GetLeftTime() int32 {
	if m != nil {
		return m.LeftTime
	}
	return 0
}

func (m *ActionTime_S2C) GetCloseTime() int32 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

type PlayerAction_C2S struct {
	DownBet              int32    `protobuf:"varint,1,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,2,opt,name=downPot,proto3,enum=msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,3,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_C2S) Reset()         { *m = PlayerAction_C2S{} }
func (m *PlayerAction_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_C2S) ProtoMessage()    {}
func (*PlayerAction_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{21}
}

func (m *PlayerAction_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_C2S.Unmarshal(m, b)
}
func (m *PlayerAction_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerAction_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_C2S.Merge(m, src)
}
func (m *PlayerAction_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_C2S.Size(m)
}
func (m *PlayerAction_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_C2S proto.InternalMessageInfo

func (m *PlayerAction_C2S) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_C2S) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XX_Pot
}

func (m *PlayerAction_C2S) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerAction_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PlayerAction_S2C struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DownBet              int32    `protobuf:"varint,2,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,3,opt,name=downPot,proto3,enum=msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,4,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	Account              float64  `protobuf:"fixed64,5,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_S2C) Reset()         { *m = PlayerAction_S2C{} }
func (m *PlayerAction_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_S2C) ProtoMessage()    {}
func (*PlayerAction_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{22}
}

func (m *PlayerAction_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_S2C.Unmarshal(m, b)
}
func (m *PlayerAction_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerAction_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_S2C.Merge(m, src)
}
func (m *PlayerAction_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_S2C.Size(m)
}
func (m *PlayerAction_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_S2C proto.InternalMessageInfo

func (m *PlayerAction_S2C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerAction_S2C) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_S2C) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XX_Pot
}

func (m *PlayerAction_S2C) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerAction_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

// 广播注池金额变化
type PotChangeMoney_S2C struct {
	PlayerData           *PlayerData   `protobuf:"bytes,1,opt,name=playerData,proto3" json:"playerData,omitempty"`
	PotMoneyCount        *DownBetMoney `protobuf:"bytes,2,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PotChangeMoney_S2C) Reset()         { *m = PotChangeMoney_S2C{} }
func (m *PotChangeMoney_S2C) String() string { return proto.CompactTextString(m) }
func (*PotChangeMoney_S2C) ProtoMessage()    {}
func (*PotChangeMoney_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{23}
}

func (m *PotChangeMoney_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotChangeMoney_S2C.Unmarshal(m, b)
}
func (m *PotChangeMoney_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotChangeMoney_S2C.Marshal(b, m, deterministic)
}
func (m *PotChangeMoney_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotChangeMoney_S2C.Merge(m, src)
}
func (m *PotChangeMoney_S2C) XXX_Size() int {
	return xxx_messageInfo_PotChangeMoney_S2C.Size(m)
}
func (m *PotChangeMoney_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PotChangeMoney_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PotChangeMoney_S2C proto.InternalMessageInfo

func (m *PotChangeMoney_S2C) GetPlayerData() *PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func (m *PotChangeMoney_S2C) GetPotMoneyCount() *DownBetMoney {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

type ResultData_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResultData_S2C) Reset()         { *m = ResultData_S2C{} }
func (m *ResultData_S2C) String() string { return proto.CompactTextString(m) }
func (*ResultData_S2C) ProtoMessage()    {}
func (*ResultData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{24}
}

func (m *ResultData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultData_S2C.Unmarshal(m, b)
}
func (m *ResultData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultData_S2C.Marshal(b, m, deterministic)
}
func (m *ResultData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData_S2C.Merge(m, src)
}
func (m *ResultData_S2C) XXX_Size() int {
	return xxx_messageInfo_ResultData_S2C.Size(m)
}
func (m *ResultData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData_S2C proto.InternalMessageInfo

func (m *ResultData_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type BankerData_C2S struct {
	Status               BankerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=msg.BankerStatus" json:"status,omitempty"`
	TakeMoney            int32        `protobuf:"varint,2,opt,name=takeMoney,proto3" json:"takeMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BankerData_C2S) Reset()         { *m = BankerData_C2S{} }
func (m *BankerData_C2S) String() string { return proto.CompactTextString(m) }
func (*BankerData_C2S) ProtoMessage()    {}
func (*BankerData_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{25}
}

func (m *BankerData_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankerData_C2S.Unmarshal(m, b)
}
func (m *BankerData_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankerData_C2S.Marshal(b, m, deterministic)
}
func (m *BankerData_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankerData_C2S.Merge(m, src)
}
func (m *BankerData_C2S) XXX_Size() int {
	return xxx_messageInfo_BankerData_C2S.Size(m)
}
func (m *BankerData_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_BankerData_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_BankerData_C2S proto.InternalMessageInfo

func (m *BankerData_C2S) GetStatus() BankerStatus {
	if m != nil {
		return m.Status
	}
	return BankerStatus_BankerNot
}

func (m *BankerData_C2S) GetTakeMoney() int32 {
	if m != nil {
		return m.TakeMoney
	}
	return 0
}

type BankerData_S2C struct {
	Banker               *PlayerData `protobuf:"bytes,1,opt,name=banker,proto3" json:"banker,omitempty"`
	TakeMoney            int32       `protobuf:"varint,2,opt,name=takeMoney,proto3" json:"takeMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BankerData_S2C) Reset()         { *m = BankerData_S2C{} }
func (m *BankerData_S2C) String() string { return proto.CompactTextString(m) }
func (*BankerData_S2C) ProtoMessage()    {}
func (*BankerData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{26}
}

func (m *BankerData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankerData_S2C.Unmarshal(m, b)
}
func (m *BankerData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankerData_S2C.Marshal(b, m, deterministic)
}
func (m *BankerData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankerData_S2C.Merge(m, src)
}
func (m *BankerData_S2C) XXX_Size() int {
	return xxx_messageInfo_BankerData_S2C.Size(m)
}
func (m *BankerData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_BankerData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_BankerData_S2C proto.InternalMessageInfo

func (m *BankerData_S2C) GetBanker() *PlayerData {
	if m != nil {
		return m.Banker
	}
	return nil
}

func (m *BankerData_S2C) GetTakeMoney() int32 {
	if m != nil {
		return m.TakeMoney
	}
	return 0
}

// 表情发送
type EmojiChat_C2S struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	GoalId               string   `protobuf:"bytes,2,opt,name=goalId,proto3" json:"goalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_C2S) Reset()         { *m = EmojiChat_C2S{} }
func (m *EmojiChat_C2S) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_C2S) ProtoMessage()    {}
func (*EmojiChat_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{27}
}

func (m *EmojiChat_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_C2S.Unmarshal(m, b)
}
func (m *EmojiChat_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_C2S.Marshal(b, m, deterministic)
}
func (m *EmojiChat_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_C2S.Merge(m, src)
}
func (m *EmojiChat_C2S) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_C2S.Size(m)
}
func (m *EmojiChat_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_C2S proto.InternalMessageInfo

func (m *EmojiChat_C2S) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_C2S) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

// 表情发送
type EmojiChat_S2C struct {
	ActNum               int32    `protobuf:"varint,1,opt,name=actNum,proto3" json:"actNum,omitempty"`
	ActId                string   `protobuf:"bytes,2,opt,name=actId,proto3" json:"actId,omitempty"`
	GoalId               string   `protobuf:"bytes,3,opt,name=goalId,proto3" json:"goalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmojiChat_S2C) Reset()         { *m = EmojiChat_S2C{} }
func (m *EmojiChat_S2C) String() string { return proto.CompactTextString(m) }
func (*EmojiChat_S2C) ProtoMessage()    {}
func (*EmojiChat_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{28}
}

func (m *EmojiChat_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmojiChat_S2C.Unmarshal(m, b)
}
func (m *EmojiChat_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmojiChat_S2C.Marshal(b, m, deterministic)
}
func (m *EmojiChat_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmojiChat_S2C.Merge(m, src)
}
func (m *EmojiChat_S2C) XXX_Size() int {
	return xxx_messageInfo_EmojiChat_S2C.Size(m)
}
func (m *EmojiChat_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EmojiChat_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EmojiChat_S2C proto.InternalMessageInfo

func (m *EmojiChat_S2C) GetActNum() int32 {
	if m != nil {
		return m.ActNum
	}
	return 0
}

func (m *EmojiChat_S2C) GetActId() string {
	if m != nil {
		return m.ActId
	}
	return ""
}

func (m *EmojiChat_S2C) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

type BankerList struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TakeMoney            int32    `protobuf:"varint,2,opt,name=takeMoney,proto3" json:"takeMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankerList) Reset()         { *m = BankerList{} }
func (m *BankerList) String() string { return proto.CompactTextString(m) }
func (*BankerList) ProtoMessage()    {}
func (*BankerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{29}
}

func (m *BankerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankerList.Unmarshal(m, b)
}
func (m *BankerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankerList.Marshal(b, m, deterministic)
}
func (m *BankerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankerList.Merge(m, src)
}
func (m *BankerList) XXX_Size() int {
	return xxx_messageInfo_BankerList.Size(m)
}
func (m *BankerList) XXX_DiscardUnknown() {
	xxx_messageInfo_BankerList.DiscardUnknown(m)
}

var xxx_messageInfo_BankerList proto.InternalMessageInfo

func (m *BankerList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BankerList) GetTakeMoney() int32 {
	if m != nil {
		return m.TakeMoney
	}
	return 0
}

// 发送时间(之後拿掉換成Action就好)
type SendActTime_S2C struct {
	StartTime            int32         `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	GameTime             int32         `protobuf:"varint,2,opt,name=gameTime,proto3" json:"gameTime,omitempty"`
	GameStep             GameStep      `protobuf:"varint,3,opt,name=gameStep,proto3,enum=msg.GameStep" json:"gameStep,omitempty"`
	BankerList           []*BankerList `protobuf:"bytes,4,rep,name=bankerList,proto3" json:"bankerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendActTime_S2C) Reset()         { *m = SendActTime_S2C{} }
func (m *SendActTime_S2C) String() string { return proto.CompactTextString(m) }
func (*SendActTime_S2C) ProtoMessage()    {}
func (*SendActTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{30}
}

func (m *SendActTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActTime_S2C.Unmarshal(m, b)
}
func (m *SendActTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActTime_S2C.Marshal(b, m, deterministic)
}
func (m *SendActTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActTime_S2C.Merge(m, src)
}
func (m *SendActTime_S2C) XXX_Size() int {
	return xxx_messageInfo_SendActTime_S2C.Size(m)
}
func (m *SendActTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_SendActTime_S2C proto.InternalMessageInfo

func (m *SendActTime_S2C) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *SendActTime_S2C) GetGameTime() int32 {
	if m != nil {
		return m.GameTime
	}
	return 0
}

func (m *SendActTime_S2C) GetGameStep() GameStep {
	if m != nil {
		return m.GameStep
	}
	return GameStep_XX_Step
}

func (m *SendActTime_S2C) GetBankerList() []*BankerList {
	if m != nil {
		return m.BankerList
	}
	return nil
}

type ChangeRoomType_S2C struct {
	Room01               bool     `protobuf:"varint,1,opt,name=room01,proto3" json:"room01,omitempty"`
	Room02               bool     `protobuf:"varint,2,opt,name=room02,proto3" json:"room02,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRoomType_S2C) Reset()         { *m = ChangeRoomType_S2C{} }
func (m *ChangeRoomType_S2C) String() string { return proto.CompactTextString(m) }
func (*ChangeRoomType_S2C) ProtoMessage()    {}
func (*ChangeRoomType_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{31}
}

func (m *ChangeRoomType_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRoomType_S2C.Unmarshal(m, b)
}
func (m *ChangeRoomType_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRoomType_S2C.Marshal(b, m, deterministic)
}
func (m *ChangeRoomType_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRoomType_S2C.Merge(m, src)
}
func (m *ChangeRoomType_S2C) XXX_Size() int {
	return xxx_messageInfo_ChangeRoomType_S2C.Size(m)
}
func (m *ChangeRoomType_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRoomType_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRoomType_S2C proto.InternalMessageInfo

func (m *ChangeRoomType_S2C) GetRoom01() bool {
	if m != nil {
		return m.Room01
	}
	return false
}

func (m *ChangeRoomType_S2C) GetRoom02() bool {
	if m != nil {
		return m.Room02
	}
	return false
}

type ErrorMsg_S2C struct {
	MsgData              string   `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData,omitempty"`
	LimitNum             float64  `protobuf:"fixed64,2,opt,name=limitNum,proto3" json:"limitNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMsg_S2C) Reset()         { *m = ErrorMsg_S2C{} }
func (m *ErrorMsg_S2C) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg_S2C) ProtoMessage()    {}
func (*ErrorMsg_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{32}
}

func (m *ErrorMsg_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMsg_S2C.Unmarshal(m, b)
}
func (m *ErrorMsg_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMsg_S2C.Marshal(b, m, deterministic)
}
func (m *ErrorMsg_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMsg_S2C.Merge(m, src)
}
func (m *ErrorMsg_S2C) XXX_Size() int {
	return xxx_messageInfo_ErrorMsg_S2C.Size(m)
}
func (m *ErrorMsg_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMsg_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMsg_S2C proto.InternalMessageInfo

func (m *ErrorMsg_S2C) GetMsgData() string {
	if m != nil {
		return m.MsgData
	}
	return ""
}

func (m *ErrorMsg_S2C) GetLimitNum() float64 {
	if m != nil {
		return m.LimitNum
	}
	return 0
}

type ShowTableInfo_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowTableInfo_C2S) Reset()         { *m = ShowTableInfo_C2S{} }
func (m *ShowTableInfo_C2S) String() string { return proto.CompactTextString(m) }
func (*ShowTableInfo_C2S) ProtoMessage()    {}
func (*ShowTableInfo_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{33}
}

func (m *ShowTableInfo_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTableInfo_C2S.Unmarshal(m, b)
}
func (m *ShowTableInfo_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTableInfo_C2S.Marshal(b, m, deterministic)
}
func (m *ShowTableInfo_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTableInfo_C2S.Merge(m, src)
}
func (m *ShowTableInfo_C2S) XXX_Size() int {
	return xxx_messageInfo_ShowTableInfo_C2S.Size(m)
}
func (m *ShowTableInfo_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTableInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTableInfo_C2S proto.InternalMessageInfo

type ShowTableInfo_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShowTableInfo_S2C) Reset()         { *m = ShowTableInfo_S2C{} }
func (m *ShowTableInfo_S2C) String() string { return proto.CompactTextString(m) }
func (*ShowTableInfo_S2C) ProtoMessage()    {}
func (*ShowTableInfo_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{34}
}

func (m *ShowTableInfo_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowTableInfo_S2C.Unmarshal(m, b)
}
func (m *ShowTableInfo_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowTableInfo_S2C.Marshal(b, m, deterministic)
}
func (m *ShowTableInfo_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowTableInfo_S2C.Merge(m, src)
}
func (m *ShowTableInfo_S2C) XXX_Size() int {
	return xxx_messageInfo_ShowTableInfo_S2C.Size(m)
}
func (m *ShowTableInfo_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowTableInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_ShowTableInfo_S2C proto.InternalMessageInfo

func (m *ShowTableInfo_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

// 异地登陆时被踢，此后不能再自动重连
type KickedOutPush struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Reason               int32    `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickedOutPush) Reset()         { *m = KickedOutPush{} }
func (m *KickedOutPush) String() string { return proto.CompactTextString(m) }
func (*KickedOutPush) ProtoMessage()    {}
func (*KickedOutPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{35}
}

func (m *KickedOutPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickedOutPush.Unmarshal(m, b)
}
func (m *KickedOutPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickedOutPush.Marshal(b, m, deterministic)
}
func (m *KickedOutPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickedOutPush.Merge(m, src)
}
func (m *KickedOutPush) XXX_Size() int {
	return xxx_messageInfo_KickedOutPush.Size(m)
}
func (m *KickedOutPush) XXX_DiscardUnknown() {
	xxx_messageInfo_KickedOutPush.DiscardUnknown(m)
}

var xxx_messageInfo_KickedOutPush proto.InternalMessageInfo

func (m *KickedOutPush) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *KickedOutPush) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *KickedOutPush) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

//直播玩家更新餘額
type ZhiBoUpdateBalancePush struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Balance              float64  `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	LockMoney            float64  `protobuf:"fixed64,4,opt,name=lockMoney,proto3" json:"lockMoney,omitempty"`
	GiftMoney            float64  `protobuf:"fixed64,5,opt,name=giftMoney,proto3" json:"giftMoney,omitempty"`
	UserID               int32    `protobuf:"varint,6,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhiBoUpdateBalancePush) Reset()         { *m = ZhiBoUpdateBalancePush{} }
func (m *ZhiBoUpdateBalancePush) String() string { return proto.CompactTextString(m) }
func (*ZhiBoUpdateBalancePush) ProtoMessage()    {}
func (*ZhiBoUpdateBalancePush) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{36}
}

func (m *ZhiBoUpdateBalancePush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhiBoUpdateBalancePush.Unmarshal(m, b)
}
func (m *ZhiBoUpdateBalancePush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhiBoUpdateBalancePush.Marshal(b, m, deterministic)
}
func (m *ZhiBoUpdateBalancePush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhiBoUpdateBalancePush.Merge(m, src)
}
func (m *ZhiBoUpdateBalancePush) XXX_Size() int {
	return xxx_messageInfo_ZhiBoUpdateBalancePush.Size(m)
}
func (m *ZhiBoUpdateBalancePush) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhiBoUpdateBalancePush.DiscardUnknown(m)
}

var xxx_messageInfo_ZhiBoUpdateBalancePush proto.InternalMessageInfo

func (m *ZhiBoUpdateBalancePush) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *ZhiBoUpdateBalancePush) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ZhiBoUpdateBalancePush) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ZhiBoUpdateBalancePush) GetLockMoney() float64 {
	if m != nil {
		return m.LockMoney
	}
	return 0
}

func (m *ZhiBoUpdateBalancePush) GetGiftMoney() float64 {
	if m != nil {
		return m.GiftMoney
	}
	return 0
}

func (m *ZhiBoUpdateBalancePush) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("msg.GameStep", GameStep_name, GameStep_value)
	proto.RegisterEnum("msg.PlayerStatus", PlayerStatus_name, PlayerStatus_value)
	proto.RegisterEnum("msg.BankerStatus", BankerStatus_name, BankerStatus_value)
	proto.RegisterEnum("msg.PotType", PotType_name, PotType_value)
	proto.RegisterEnum("msg.CardsType", CardsType_name, CardsType_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*Login_C2S)(nil), "msg.Login_C2S")
	proto.RegisterType((*Login_S2C)(nil), "msg.Login_S2C")
	proto.RegisterType((*Logout_C2S)(nil), "msg.Logout_C2S")
	proto.RegisterType((*Logout_S2C)(nil), "msg.Logout_S2C")
	proto.RegisterType((*PotWinList)(nil), "msg.PotWinList")
	proto.RegisterType((*PlayerData)(nil), "msg.PlayerData")
	proto.RegisterType((*DownBetMoney)(nil), "msg.DownBetMoney")
	proto.RegisterType((*DownBetHistory)(nil), "msg.DownBetHistory")
	proto.RegisterType((*LotteryResult)(nil), "msg.LotteryResult")
	proto.RegisterType((*LotteryResultFX)(nil), "msg.LotteryResultFX")
	proto.RegisterType((*LotteryData)(nil), "msg.LotteryData")
	proto.RegisterType((*RoomData)(nil), "msg.RoomData")
	proto.RegisterType((*JoinRoom_C2S)(nil), "msg.JoinRoom_C2S")
	proto.RegisterType((*JoinRoom_S2C)(nil), "msg.JoinRoom_S2C")
	proto.RegisterType((*EnterRoom_S2C)(nil), "msg.EnterRoom_S2C")
	proto.RegisterType((*LeaveRoom_C2S)(nil), "msg.LeaveRoom_C2S")
	proto.RegisterType((*LeaveRoom_S2C)(nil), "msg.LeaveRoom_S2C")
	proto.RegisterType((*ActionTime_S2C)(nil), "msg.ActionTime_S2C")
	proto.RegisterType((*PlayerAction_C2S)(nil), "msg.PlayerAction_C2S")
	proto.RegisterType((*PlayerAction_S2C)(nil), "msg.PlayerAction_S2C")
	proto.RegisterType((*PotChangeMoney_S2C)(nil), "msg.PotChangeMoney_S2C")
	proto.RegisterType((*ResultData_S2C)(nil), "msg.ResultData_S2C")
	proto.RegisterType((*BankerData_C2S)(nil), "msg.BankerData_C2S")
	proto.RegisterType((*BankerData_S2C)(nil), "msg.BankerData_S2C")
	proto.RegisterType((*EmojiChat_C2S)(nil), "msg.EmojiChat_C2S")
	proto.RegisterType((*EmojiChat_S2C)(nil), "msg.EmojiChat_S2C")
	proto.RegisterType((*BankerList)(nil), "msg.BankerList")
	proto.RegisterType((*SendActTime_S2C)(nil), "msg.SendActTime_S2C")
	proto.RegisterType((*ChangeRoomType_S2C)(nil), "msg.ChangeRoomType_S2C")
	proto.RegisterType((*ErrorMsg_S2C)(nil), "msg.ErrorMsg_S2C")
	proto.RegisterType((*ShowTableInfo_C2S)(nil), "msg.ShowTableInfo_C2S")
	proto.RegisterType((*ShowTableInfo_S2C)(nil), "msg.ShowTableInfo_S2C")
	proto.RegisterType((*KickedOutPush)(nil), "msg.KickedOutPush")
	proto.RegisterType((*ZhiBoUpdateBalancePush)(nil), "msg.ZhiBoUpdateBalancePush")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 1872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x6f, 0xdc, 0xc8,
	0x11, 0x36, 0x87, 0xf3, 0xac, 0x79, 0xa8, 0xdd, 0x96, 0xb5, 0x5c, 0x63, 0xb1, 0x10, 0x88, 0xc0,
	0x91, 0x75, 0xd8, 0x5d, 0x33, 0x08, 0x82, 0xd8, 0x40, 0x92, 0xd5, 0xc8, 0x76, 0x66, 0x23, 0x39,
	0x03, 0x8e, 0x0c, 0x69, 0x93, 0x83, 0x41, 0xcd, 0xb4, 0x39, 0xcc, 0xcc, 0xb0, 0x05, 0xb2, 0x67,
	0x0d, 0x21, 0x40, 0x90, 0x9f, 0x10, 0xec, 0x31, 0xa7, 0xdc, 0xf2, 0x13, 0x02, 0xe4, 0x37, 0xe4,
	0x9e, 0x5b, 0x7e, 0x49, 0x0e, 0x41, 0xf5, 0x83, 0xd3, 0xa4, 0x1e, 0x7e, 0x20, 0x87, 0xbd, 0xb1,
	0xbe, 0xaa, 0xee, 0xae, 0xaa, 0xae, 0x57, 0x13, 0x3a, 0xab, 0x3c, 0xfe, 0xe2, 0x22, 0xe3, 0x82,
	0x53, 0x77, 0x95, 0xc7, 0x7e, 0x13, 0xea, 0xe3, 0x24, 0x8d, 0xfd, 0x87, 0x50, 0x1f, 0xf3, 0x34,
	0xa6, 0x9f, 0x03, 0xe4, 0x2c, 0xfb, 0x8e, 0x65, 0x27, 0xc9, 0x8a, 0x79, 0xce, 0xae, 0xb3, 0xe7,
	0x86, 0x16, 0xe2, 0x2f, 0x01, 0xc6, 0xcb, 0xe8, 0x92, 0x65, 0xa3, 0xf4, 0x0d, 0xa7, 0x03, 0xa8,
	0x8d, 0x66, 0x52, 0xaa, 0x13, 0xd6, 0x46, 0x33, 0xfa, 0x00, 0xda, 0x69, 0x32, 0x5d, 0xbc, 0x8c,
	0x56, 0xcc, 0xab, 0x49, 0xb4, 0xa0, 0xa9, 0x07, 0xad, 0x39, 0x8b, 0x66, 0xa3, 0x55, 0xec, 0xb9,
	0x92, 0x65, 0x48, 0xe4, 0x44, 0xd3, 0x29, 0x5f, 0xa7, 0xc2, 0xab, 0xef, 0x3a, 0x7b, 0x4e, 0x68,
	0x48, 0xff, 0x18, 0x3a, 0x47, 0x3c, 0x4e, 0xd2, 0xd7, 0xc3, 0x60, 0x72, 0xdd, 0x61, 0xe3, 0x28,
	0xcf, 0x4f, 0x79, 0x36, 0x33, 0x87, 0x19, 0x9a, 0x6e, 0x43, 0xe3, 0x84, 0x2f, 0x58, 0xaa, 0x8f,
	0x52, 0x84, 0xff, 0x2f, 0xc7, 0xec, 0x37, 0x09, 0x86, 0xf4, 0x4b, 0x80, 0x8b, 0xc2, 0x14, 0xb9,
	0x6f, 0x37, 0xd8, 0xfa, 0x02, 0xfd, 0xb3, 0xb1, 0x30, 0xb4, 0x44, 0xf0, 0xc0, 0xf3, 0x68, 0xba,
	0xc8, 0x38, 0x5f, 0xc9, 0x03, 0xdb, 0x61, 0x41, 0xd3, 0x5d, 0xe8, 0xaa, 0x55, 0x2f, 0xd7, 0xab,
	0xf0, 0xb1, 0x3c, 0xb6, 0x11, 0xda, 0x50, 0x59, 0x22, 0x90, 0x96, 0x96, 0x24, 0x02, 0xba, 0x03,
	0x4d, 0xdc, 0xeb, 0xab, 0xc7, 0x5e, 0x43, 0xee, 0xae, 0xa9, 0x02, 0x0f, 0xbc, 0xa6, 0x85, 0x07,
	0x7e, 0x0f, 0xe0, 0x88, 0xc7, 0x7c, 0x2d, 0xd0, 0x3d, 0x16, 0x35, 0x09, 0x86, 0xfe, 0x5f, 0x1c,
	0x80, 0x31, 0x17, 0xa7, 0x49, 0x7a, 0x94, 0xe4, 0x82, 0x7e, 0x06, 0x9d, 0x8c, 0xe5, 0xeb, 0xa5,
	0x78, 0xb9, 0x5e, 0x49, 0x53, 0x1b, 0xe1, 0x06, 0x90, 0x86, 0x25, 0xf1, 0x64, 0x15, 0x2d, 0x97,
	0xd2, 0xb0, 0x46, 0x58, 0xd0, 0xb8, 0x32, 0x4f, 0xd2, 0x43, 0xbe, 0x3e, 0x5f, 0x32, 0x6d, 0xd6,
	0x06, 0xa0, 0xfb, 0xd0, 0x9e, 0x46, 0xd9, 0xec, 0xe4, 0xf2, 0x82, 0x49, 0x8b, 0x06, 0xc1, 0x40,
	0x7a, 0x70, 0x18, 0x65, 0xb3, 0x1c, 0xd1, 0xb0, 0xe0, 0xfb, 0xff, 0x71, 0x4d, 0xec, 0x1c, 0x46,
	0x22, 0xfa, 0x70, 0xf7, 0xff, 0x14, 0x7a, 0x33, 0xfe, 0x36, 0x3d, 0x60, 0xe2, 0x98, 0xa7, 0xec,
	0x52, 0x6a, 0xda, 0x0d, 0xee, 0xca, 0x25, 0x87, 0x16, 0x23, 0x2c, 0x89, 0xd1, 0x47, 0xd0, 0xcc,
	0x45, 0x24, 0xd6, 0xb9, 0xd4, 0x7e, 0xa0, 0x17, 0xa8, 0x33, 0x26, 0x92, 0x11, 0x6a, 0x01, 0xbc,
	0xa2, 0xf3, 0x28, 0x5d, 0xb0, 0x4c, 0x1d, 0xa0, 0x82, 0xd1, 0x86, 0x36, 0x12, 0x43, 0x19, 0xae,
	0x0d, 0x75, 0x89, 0x16, 0x44, 0x7d, 0xe8, 0x09, 0x2e, 0xa2, 0xa5, 0xd6, 0x48, 0x5e, 0x59, 0x23,
	0x2c, 0x61, 0xf4, 0x47, 0xd0, 0x7f, 0x9b, 0xa4, 0x27, 0x08, 0xa9, 0x7d, 0x5a, 0x52, 0xa8, 0x0c,
	0xe2, 0x59, 0xea, 0x8a, 0x94, 0x36, 0x6d, 0xa5, 0x8d, 0x05, 0xd1, 0xa7, 0x30, 0xd0, 0xa6, 0xfe,
	0x3a, 0xc9, 0x05, 0xcf, 0x2e, 0x3d, 0xd8, 0x75, 0xf7, 0xba, 0xc1, 0x3d, 0xdb, 0x27, 0x9a, 0x15,
	0x56, 0x44, 0xf1, 0xd2, 0x47, 0xf9, 0xd7, 0x53, 0x91, 0xf0, 0xd4, 0xeb, 0xaa, 0x68, 0x36, 0xb4,
	0xe2, 0x1d, 0x48, 0xab, 0xbc, 0x9e, 0xe1, 0x29, 0x1a, 0xb3, 0x75, 0x94, 0x87, 0xfc, 0x9c, 0x0b,
	0xaf, 0x2f, 0x59, 0x86, 0xf4, 0xbf, 0xaf, 0x41, 0xcf, 0xbe, 0x08, 0x2c, 0x26, 0x07, 0x49, 0x6c,
	0x3c, 0xa1, 0xc2, 0xce, 0x42, 0xd0, 0x57, 0x32, 0xc8, 0x8c, 0x84, 0x8a, 0xbd, 0x12, 0x86, 0xbe,
	0x9a, 0x24, 0x69, 0xbc, 0x64, 0x46, 0x48, 0xc5, 0x60, 0x19, 0x44, 0x29, 0x15, 0x91, 0x46, 0x4a,
	0xa5, 0x57, 0x19, 0x94, 0x29, 0x18, 0x25, 0x99, 0x91, 0xd1, 0xb7, 0x67, 0x41, 0x74, 0x0f, 0xb6,
	0x26, 0x22, 0x8b, 0x92, 0x78, 0x2e, 0xca, 0x17, 0x58, 0x85, 0xe9, 0x43, 0x18, 0x1c, 0x31, 0x7e,
	0x11, 0x65, 0x33, 0x23, 0xa8, 0x2e, 0xb1, 0x82, 0xfa, 0xff, 0x76, 0x60, 0x50, 0xbe, 0x09, 0xf4,
	0xa0, 0x48, 0x56, 0xec, 0xf9, 0x4a, 0xe8, 0x6a, 0x66, 0x48, 0x99, 0xe9, 0x2c, 0xc7, 0x1c, 0xad,
	0xed, 0xba, 0x7b, 0x8d, 0x50, 0x53, 0x74, 0x5f, 0xe2, 0xeb, 0xa5, 0xb2, 0xbe, 0x1b, 0x50, 0x79,
	0xc1, 0x47, 0x5c, 0x08, 0x96, 0x5d, 0x86, 0x92, 0x13, 0x6a, 0x09, 0xfa, 0x15, 0xb4, 0xd5, 0xd7,
	0xf3, 0x33, 0xe9, 0x85, 0x6e, 0xb0, 0x7d, 0x55, 0xfa, 0xf9, 0x59, 0x58, 0x48, 0x5d, 0x49, 0xac,
	0xc6, 0x7b, 0x25, 0x96, 0x7f, 0x0a, 0xfd, 0xd2, 0x9e, 0x18, 0x35, 0xcb, 0xf5, 0x74, 0x71, 0xb9,
	0xa9, 0x31, 0x05, 0x5d, 0x2a, 0x14, 0xb5, 0x77, 0x14, 0x8a, 0x6f, 0x61, 0xab, 0xa2, 0xec, 0xff,
	0x6d, 0xeb, 0x7f, 0x38, 0xd0, 0xd5, 0x7b, 0xcb, 0x22, 0xf4, 0x43, 0xbb, 0x0a, 0x99, 0x5c, 0x47,
	0xc9, 0xfa, 0x9b, 0xb5, 0xee, 0x01, 0x86, 0xf4, 0xbf, 0x77, 0xa1, 0x1d, 0x72, 0xbe, 0x92, 0x6a,
	0xeb, 0x8e, 0x50, 0xb4, 0x43, 0x4d, 0xe1, 0xf2, 0x8c, 0xaf, 0xd3, 0xd9, 0xc8, 0x74, 0x44, 0x43,
	0x6e, 0xaa, 0x2d, 0xae, 0xf7, 0x5c, 0x59, 0x26, 0xec, 0x6a, 0x8b, 0x70, 0x68, 0x89, 0xa0, 0xc7,
	0xe3, 0x68, 0xc5, 0xe4, 0x18, 0xa0, 0x92, 0xa9, 0xa0, 0xe9, 0x23, 0xc5, 0x9b, 0x08, 0x76, 0x21,
	0xd5, 0x1c, 0x04, 0x7d, 0xb9, 0xd5, 0x0b, 0x0d, 0x86, 0x05, 0x7b, 0xd3, 0x78, 0x46, 0x29, 0xa6,
	0x92, 0xbb, 0x69, 0x3c, 0xa3, 0x54, 0xd0, 0x9f, 0x41, 0xff, 0x82, 0xab, 0x70, 0xda, 0x14, 0xc2,
	0x6b, 0x43, 0xaf, 0x2c, 0x47, 0x03, 0xe8, 0xce, 0x55, 0x36, 0x49, 0x7b, 0xda, 0xd2, 0x1e, 0x62,
	0x3b, 0x57, 0x1a, 0x64, 0x0b, 0xd1, 0xc7, 0xd0, 0x15, 0xd1, 0xf9, 0x92, 0x29, 0x83, 0xbd, 0xce,
	0xf5, 0x3e, 0xb0, 0x65, 0xb0, 0x80, 0x8d, 0x59, 0x96, 0xf0, 0x99, 0x0c, 0x04, 0x90, 0x2e, 0xb5,
	0x10, 0xff, 0x21, 0xf4, 0xbe, 0xe1, 0x49, 0x8a, 0xf7, 0x22, 0x47, 0x94, 0x1b, 0xee, 0xc5, 0xcf,
	0x2d, 0x39, 0x1c, 0x3d, 0x1e, 0x41, 0x3b, 0xd3, 0x77, 0xa9, 0x3b, 0x9f, 0x72, 0xa0, 0xb9, 0xe0,
	0xb0, 0x60, 0xcb, 0xc8, 0x67, 0x6f, 0x84, 0xbc, 0x07, 0xdd, 0x9b, 0x0d, 0x8d, 0xce, 0x9d, 0x2e,
	0x79, 0xae, 0x2e, 0x49, 0xf7, 0xe6, 0x02, 0xf0, 0x9f, 0x40, 0xff, 0x59, 0x2a, 0x58, 0xf6, 0x11,
	0xa7, 0xfa, 0x5b, 0xd0, 0x3f, 0x62, 0xd1, 0x77, 0xcc, 0x58, 0xe6, 0xff, 0xca, 0x06, 0x3e, 0x66,
	0x7a, 0xf2, 0xff, 0xe6, 0xc0, 0x40, 0xb5, 0x17, 0xd4, 0xce, 0x28, 0x54, 0xc4, 0x91, 0x73, 0x7b,
	0x1c, 0xd9, 0xba, 0xd7, 0xde, 0xdf, 0x63, 0xee, 0x6d, 0x1e, 0xab, 0x57, 0x3d, 0xf6, 0x67, 0x07,
	0x88, 0xd2, 0x5e, 0x29, 0x2a, 0xef, 0xd4, 0x83, 0xd6, 0xac, 0xd4, 0xc1, 0x0c, 0x49, 0x1f, 0x2a,
	0xce, 0x98, 0x0b, 0x5d, 0x77, 0x7a, 0xca, 0x7e, 0x2e, 0x64, 0xd5, 0x31, 0xcc, 0x52, 0xa7, 0x75,
	0x2b, 0x9d, 0x56, 0x0d, 0xb5, 0x75, 0x33, 0xd4, 0xfa, 0x7f, 0xad, 0xaa, 0x80, 0x7e, 0xaa, 0x4e,
	0xbe, 0x96, 0x4a, 0xb5, 0x1b, 0x55, 0x72, 0xdf, 0x57, 0xa5, 0x7a, 0x45, 0x25, 0x6b, 0x1c, 0x6f,
	0x94, 0xc7, 0xf1, 0x3f, 0x01, 0x1d, 0x73, 0x31, 0x9c, 0x47, 0x69, 0xcc, 0x64, 0x32, 0x96, 0x23,
	0xc1, 0x0a, 0xac, 0x5b, 0x4b, 0xcb, 0x95, 0xac, 0xaf, 0xbd, 0x5f, 0xd6, 0xfb, 0x4f, 0x61, 0xa0,
	0x6a, 0x26, 0x6e, 0xf3, 0xa1, 0x21, 0xfd, 0x2d, 0x0c, 0xd4, 0x04, 0x23, 0x17, 0xe3, 0xcd, 0x6e,
	0x26, 0x43, 0xc7, 0x9a, 0x0c, 0x95, 0x50, 0x65, 0x32, 0xfc, 0x0c, 0x3a, 0x22, 0x5a, 0xb0, 0xcd,
	0xe0, 0xd9, 0x08, 0x37, 0x80, 0x7f, 0x5a, 0xda, 0x1a, 0xf5, 0xfa, 0x31, 0x34, 0xd5, 0x50, 0x78,
	0x93, 0x3f, 0x34, 0xfb, 0x1d, 0x1b, 0xff, 0x12, 0xfa, 0xcf, 0x56, 0xfc, 0x0f, 0xc9, 0x70, 0x1e,
	0x09, 0x53, 0x60, 0xa2, 0xa9, 0x35, 0xc4, 0x6b, 0x0a, 0xf1, 0x98, 0x47, 0xcb, 0xa2, 0xee, 0x6b,
	0xca, 0x7f, 0x65, 0x6f, 0x80, 0x8a, 0xdd, 0xb4, 0xc1, 0x36, 0x34, 0xa2, 0xa9, 0x28, 0xd6, 0x2b,
	0xc2, 0xda, 0xd6, 0x2d, 0x6d, 0xfb, 0x04, 0x40, 0x19, 0x2c, 0x1f, 0x17, 0xd5, 0xf0, 0xbc, 0xdd,
	0xa6, 0xbf, 0x3b, 0xb0, 0x35, 0x61, 0xe9, 0xec, 0xeb, 0xa9, 0x28, 0x0a, 0x01, 0x3e, 0x32, 0x44,
	0x94, 0x89, 0xe2, 0xd1, 0x89, 0x8f, 0x0c, 0x03, 0x94, 0x5a, 0x51, 0xed, 0x96, 0x56, 0xe4, 0xde,
	0x5e, 0x42, 0xbe, 0x04, 0x38, 0x2f, 0x94, 0xf6, 0xea, 0x56, 0xf9, 0xdf, 0xd8, 0x12, 0x5a, 0x22,
	0xfe, 0x21, 0x50, 0x15, 0xeb, 0x18, 0x4d, 0x98, 0x3f, 0xc6, 0x83, 0xfa, 0x95, 0xe6, 0xdc, 0xf0,
	0x4a, 0xab, 0x95, 0x5e, 0x69, 0x87, 0xd0, 0x7b, 0x96, 0x65, 0x3c, 0x3b, 0xce, 0x63, 0xb9, 0xde,
	0x83, 0xd6, 0x2a, 0x8f, 0x8b, 0x88, 0xed, 0x84, 0x86, 0x94, 0x85, 0x2b, 0x59, 0x25, 0x42, 0x0d,
	0x1d, 0x98, 0x79, 0x05, 0xed, 0xdf, 0x83, 0xbb, 0x93, 0x39, 0x7f, 0x7b, 0x82, 0xcd, 0x09, 0xcb,
	0xa9, 0x2c, 0xca, 0xbf, 0xa8, 0x82, 0x1f, 0x98, 0x12, 0xbf, 0x87, 0xfe, 0x6f, 0x92, 0xe9, 0x82,
	0xcd, 0x7e, 0xbb, 0x16, 0xe3, 0x75, 0x3e, 0x7f, 0xd7, 0xeb, 0x9f, 0x52, 0xa8, 0x4f, 0xf9, 0xcc,
	0xdc, 0x82, 0xfc, 0x56, 0x83, 0x52, 0x94, 0xeb, 0xda, 0x26, 0x07, 0x25, 0xa4, 0xfc, 0x7f, 0x3a,
	0xb0, 0xf3, 0xbb, 0x79, 0x72, 0xc0, 0x5f, 0x5d, 0xcc, 0x22, 0xc1, 0x0e, 0xa2, 0x65, 0x94, 0x4e,
	0xd9, 0x47, 0x1f, 0xe3, 0x41, 0xeb, 0x5c, 0x6d, 0x21, 0xcf, 0x71, 0x42, 0x43, 0x62, 0xf0, 0x2c,
	0xf9, 0x74, 0x61, 0xbf, 0xd9, 0x36, 0x00, 0x72, 0xe3, 0xe4, 0x8d, 0x35, 0xd9, 0x3a, 0xe1, 0x06,
	0x40, 0xe5, 0xd7, 0x39, 0xcb, 0x46, 0x87, 0x7a, 0xcc, 0xd7, 0xd4, 0xfe, 0x7f, 0xeb, 0xd0, 0x39,
	0x66, 0x79, 0x1e, 0xc5, 0x6c, 0x74, 0x48, 0x7b, 0xd0, 0x3e, 0x9e, 0xbc, 0x78, 0x3d, 0x4e, 0xd2,
	0x98, 0xdc, 0x29, 0x28, 0x9e, 0xc6, 0xc4, 0xa1, 0x77, 0xa1, 0x8f, 0x54, 0xf1, 0x9b, 0x82, 0xd4,
	0xca, 0xd0, 0x24, 0x18, 0x12, 0x97, 0x52, 0x18, 0x68, 0x48, 0x3f, 0xd7, 0x49, 0xbd, 0x82, 0xa1,
	0x5c, 0x83, 0x6e, 0x03, 0x41, 0xcc, 0x1e, 0x2a, 0x48, 0xf3, 0x0a, 0x8a, 0xb2, 0x2d, 0x7a, 0x1f,
	0xee, 0x22, 0x5a, 0xea, 0xf1, 0xa4, 0x6d, 0xe0, 0x52, 0xfb, 0x26, 0x9d, 0xab, 0x30, 0x4a, 0x03,
	0xdd, 0x01, 0x8a, 0x70, 0xb9, 0x31, 0x93, 0x2e, 0xf5, 0x60, 0x5b, 0x1a, 0x59, 0xe9, 0x86, 0xa4,
	0x77, 0x2d, 0x07, 0xd7, 0xf4, 0xe9, 0x03, 0xd8, 0x51, 0x8e, 0xa9, 0xb6, 0x08, 0x32, 0x30, 0xe7,
	0x94, 0xcb, 0x37, 0xd9, 0x32, 0x78, 0xb9, 0x32, 0x13, 0x72, 0x0d, 0x8e, 0xf2, 0x77, 0x0b, 0xa3,
	0xed, 0xaa, 0x48, 0xe8, 0x55, 0x18, 0xa5, 0xef, 0xd1, 0x4f, 0xe0, 0x1e, 0xc2, 0x95, 0x72, 0x43,
	0xb6, 0x8d, 0xaa, 0x57, 0xd3, 0x9b, 0xdc, 0x37, 0xde, 0xb6, 0x93, 0x96, 0xec, 0xd0, 0x4f, 0xe1,
	0xbe, 0xdc, 0xaa, 0x9a, 0x84, 0xe4, 0x93, 0xeb, 0x59, 0xb8, 0xca, 0x33, 0x7a, 0x95, 0xb2, 0x8c,
	0x7c, 0x4a, 0x3f, 0x87, 0x07, 0x08, 0x5f, 0x9f, 0x1e, 0xe4, 0xc1, 0xfe, 0x02, 0xda, 0xa6, 0x80,
	0xd1, 0x2e, 0xb4, 0xce, 0xce, 0x5e, 0xe3, 0x27, 0xb9, 0x43, 0x01, 0x9a, 0xca, 0x25, 0xc4, 0x41,
	0x86, 0xfa, 0x0e, 0x48, 0x0d, 0x09, 0xdd, 0x39, 0x89, 0x8b, 0x52, 0x13, 0x26, 0xc4, 0x92, 0x91,
	0x3a, 0xed, 0x40, 0x63, 0x88, 0x03, 0x0e, 0x69, 0x20, 0xfc, 0x82, 0x89, 0x90, 0xe5, 0xa4, 0x89,
	0xb0, 0x7c, 0x57, 0x90, 0xd6, 0xfe, 0x13, 0xe8, 0xd9, 0x7f, 0x43, 0x68, 0x1f, 0x3a, 0xf2, 0x40,
	0x24, 0x54, 0xb8, 0x23, 0x1b, 0xf5, 0x21, 0x0e, 0x32, 0x4f, 0x23, 0x31, 0x9d, 0x4b, 0xb2, 0xb6,
	0xff, 0x14, 0x7a, 0x76, 0xbf, 0x44, 0xb6, 0xa2, 0x5f, 0x72, 0xa1, 0xd6, 0x2a, 0xf2, 0xd5, 0x05,
	0x71, 0xe8, 0xc0, 0x74, 0x0d, 0xd4, 0x94, 0xd4, 0xf6, 0xff, 0x08, 0x2d, 0x3d, 0x98, 0xa0, 0x6a,
	0x67, 0x67, 0x18, 0x39, 0xda, 0xc6, 0x24, 0xc6, 0x6f, 0x07, 0x37, 0x90, 0x7f, 0x03, 0x90, 0xaa,
	0xe1, 0xee, 0xea, 0xd9, 0x8f, 0xa4, 0x8b, 0xa4, 0x7a, 0xdf, 0x23, 0x59, 0x47, 0x17, 0xe0, 0x53,
	0x1e, 0x89, 0x06, 0xdd, 0x82, 0xae, 0x79, 0xb1, 0x23, 0xd0, 0xc4, 0xc3, 0xf5, 0xcb, 0x1c, 0xe9,
	0xd6, 0xfe, 0xcf, 0xa1, 0x53, 0x3c, 0x10, 0xb5, 0x8f, 0x91, 0x26, 0x77, 0xd0, 0x35, 0xf2, 0x4c,
	0xe2, 0xd0, 0x16, 0xb8, 0x07, 0x49, 0xac, 0xdc, 0xab, 0x57, 0x13, 0xf7, 0xbc, 0x29, 0xff, 0x9f,
	0xfe, 0xe4, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xd4, 0x94, 0x2d, 0x4c, 0x15, 0x00, 0x00,
}
